from ascon_hwmodel.absorb import absorb_block64_into_x0, absorb_block128_into_x0_x1
from ascon_hwmodel.bitstring import Bit, BitString, ParsedBitString, pad_bitstring, parse_bitstring
from ascon_hwmodel.byteops import (
    ParsedBytes,
    WordBytes64,
    bytes_to_u64_le,
    bytes_to_words64_le,
    pad_bytes,
    pad_bytes_as_bits,
    parse_bytes,
    parse_bytes_as_bits,
    u64_to_bytes_le,
    words64_to_bytes_le,
)
from ascon_hwmodel.domain import (
    AEAD_DOMAIN_SEPARATOR_BIT_INDEX,
    AEAD_DOMAIN_SEPARATOR_X4_MASK,
    aead_domain_separate_after_ad,
)
from ascon_hwmodel.iv import EXPECTED_IV, IV_PARAMS, IVParams, ascon_iv, assert_iv_table
from ascon_hwmodel.keyops import (
    aead128_add_key_after_initial_permutation,
    aead128_add_key_before_final_permutation,
    aead128_extract_tag_after_final_permutation,
    aead128_initial_state_before_permutation,
)
from ascon_hwmodel.p6 import ascon_p6, emit_verilog_p6_function, emit_verilog_p6_include, emit_verilog_p6_module
from ascon_hwmodel.p8 import ascon_p8, emit_verilog_p8_function, emit_verilog_p8_include, emit_verilog_p8_module
from ascon_hwmodel.p12 import ascon_p12, emit_verilog_p12_function, emit_verilog_p12_include, emit_verilog_p12_module
from ascon_hwmodel.pc import (
    ROUND_CONSTANTS,
    check_rounds,
    emit_verilog_pc_function,
    emit_verilog_pc_include,
    emit_verilog_round_constant_function,
    emit_verilog_round_constants,
    p_c,
    p_c_const_index,
    round_constant,
    round_constant_index,
)
from ascon_hwmodel.pl import (
    MASK64,
    emit_verilog_pl_function,
    emit_verilog_pl_include,
    emit_verilog_rotr64_function,
    p_l,
    rotr64,
    sigma0,
    sigma1,
    sigma2,
    sigma3,
    sigma4,
)
from ascon_hwmodel.ps import (
    SBOX,
    emit_verilog_ps_bitsliced_function,
    emit_verilog_ps_function,
    emit_verilog_ps_include,
    emit_verilog_ps_lut_function,
    emit_verilog_sbox5_lut_function,
    p_s,
    p_s_bitsliced,
    p_s_lut,
    sbox5_bits,
    sbox5_value,
)
from ascon_hwmodel.round import (
    PermutationTraceEntry,
    ascon_permutation,
    ascon_permutation_trace,
    ascon_round,
    emit_verilog_round_function,
    emit_verilog_round_include,
)
from ascon_hwmodel.state import AsconState
from ascon_hwmodel.uint import FixedUInt, U4, U8, U16, U64, U128, U320
from ascon_hwmodel.variants import AsconVariant
from ascon_hwmodel.verilog import (
    emit_verilog_aead128_add_key_after_init_function,
    emit_verilog_aead128_add_key_before_final_function,
    emit_verilog_aead128_extract_tag_function,
    emit_verilog_aead128_initial_state_function,
    emit_verilog_aux_include,
    emit_verilog_domain_key_functions,
    emit_verilog_domain_key_include,
    emit_verilog_domain_separator_function,
    emit_verilog_iv_function,
    emit_verilog_iv_include,
    emit_verilog_iv_localparams,
    emit_verilog_keyops_include,
    emit_verilog_model_include,
    emit_verilog_pad64_partial_function,
    emit_verilog_pad128_partial_function,
    emit_verilog_permutation_comb_module,
    emit_verilog_permutation_functions,
    emit_verilog_permutation_include,
    emit_verilog_state_include,
    emit_verilog_state_pack_function,
    emit_verilog_state_word_function,
    render_verilog_files,
    write_verilog_files,
)
from ascon_hwmodel.views import ByteSequenceHex, UIntHex
from ascon_hwmodel.word import Block64, Block128, Key128, Nonce128, Tag128

__all__: list[str] = [
    "AEAD_DOMAIN_SEPARATOR_BIT_INDEX",
    "AEAD_DOMAIN_SEPARATOR_X4_MASK",
    "AeadStreamKind",
    "AsconState",
    "AsconVariant",
    "Bit",
    "BitString",
    "Block64",
    "Block128",
    "ByteSequenceHex",
    "EXPECTED_IV",
    "FixedUInt",
    "IV_PARAMS",
    "IVParams",
    "Key128",
    "MASK64",
    "Nonce128",
    "ParsedBitString",
    "ParsedBytes",
    "PermutationTraceEntry",
    "ROUND_CONSTANTS",
    "SBOX",
    "Tag128",
    "U4",
    "U8",
    "U16",
    "U64",
    "U128",
    "U320",
    "UIntHex",
    "WordBytes64",
    "absorb_block64_into_x0",
    "absorb_block128_into_x0_x1",
    "aead128_add_key_after_initial_permutation",
    "aead128_add_key_before_final_permutation",
    "aead128_extract_tag_after_final_permutation",
    "aead128_initial_state_before_permutation",
    "aead_domain_separate_after_ad",
    "ascon_iv",
    "ascon_p6",
    "ascon_p8",
    "ascon_p12",
    "ascon_permutation",
    "ascon_permutation_trace",
    "ascon_round",
    "assert_iv_table",
    "AxisAeadDecryptionResult",
    "AxisAeadEncryptionResult",
    "AxisStreamBeat",
    "axis_aead128_decrypt",
    "axis_aead128_encrypt",
    "keep_mask",
    "pack_axis_beats",
    "unpack_axis_beats",
    "valid_byte_count_from_keep",
    "bytes_to_u64_le",
    "bytes_to_words64_le",
    "check_rounds",
    "emit_verilog_aead128_add_key_after_init_function",
    "emit_verilog_aead128_add_key_before_final_function",
    "emit_verilog_aead128_extract_tag_function",
    "emit_verilog_aead128_initial_state_function",
    "emit_verilog_aux_include",
    "emit_verilog_domain_key_functions",
    "emit_verilog_domain_key_include",
    "emit_verilog_domain_separator_function",
    "emit_verilog_iv_function",
    "emit_verilog_iv_include",
    "emit_verilog_iv_localparams",
    "emit_verilog_keyops_include",
    "emit_verilog_model_include",
    "emit_verilog_p6_function",
    "emit_verilog_p6_include",
    "emit_verilog_p6_module",
    "emit_verilog_p8_function",
    "emit_verilog_p8_include",
    "emit_verilog_p8_module",
    "emit_verilog_p12_function",
    "emit_verilog_p12_include",
    "emit_verilog_p12_module",
    "emit_verilog_pad64_partial_function",
    "emit_verilog_pad128_partial_function",
    "emit_verilog_pc_function",
    "emit_verilog_pc_include",
    "emit_verilog_permutation_comb_module",
    "emit_verilog_permutation_functions",
    "emit_verilog_permutation_include",
    "emit_verilog_pl_function",
    "emit_verilog_pl_include",
    "emit_verilog_ps_bitsliced_function",
    "emit_verilog_ps_function",
    "emit_verilog_ps_include",
    "emit_verilog_ps_lut_function",
    "emit_verilog_rotr64_function",
    "emit_verilog_round_constant_function",
    "emit_verilog_round_constants",
    "emit_verilog_round_function",
    "emit_verilog_round_include",
    "emit_verilog_sbox5_lut_function",
    "emit_verilog_state_include",
    "emit_verilog_state_pack_function",
    "emit_verilog_state_word_function",
    "p_c",
    "p_c_const_index",
    "p_l",
    "p_s",
    "p_s_bitsliced",
    "p_s_lut",
    "pad_bitstring",
    "pad_bytes",
    "pad_bytes_as_bits",
    "parse_bitstring",
    "parse_bytes",
    "parse_bytes_as_bits",
    "rotr64",
    "round_constant",
    "round_constant_index",
    "sbox5_bits",
    "sbox5_value",
    "sigma0",
    "sigma1",
    "sigma2",
    "sigma3",
    "sigma4",
    "u64_to_bytes_le",
    "render_verilog_files",
    "write_verilog_files",
    "words64_to_bytes_le",
]

# AEAD phase-based model
from ascon_hwmodel.aead_config import AEADConfig, AEADVariant, AEAD_CONFIGS, get_aead_config
from ascon_hwmodel.aead_init import aead_initialize, aead_initial_state_before_permutation, aead_add_key_after_initial_permutation
from ascon_hwmodel.aead_ad import aead_process_associated_data
from ascon_hwmodel.aead_plaintext import AEADPlaintextResult, aead_encrypt_plaintext
from ascon_hwmodel.aead_ciphertext import AEADCiphertextResult, aead_decrypt_ciphertext
from ascon_hwmodel.aead_final import aead_add_key_before_final_permutation, aead_extract_tag_after_final_permutation, aead_finalize
from ascon_hwmodel.aead_encrypt import AEADEncryptionResult, aead_encrypt
from ascon_hwmodel.aead_decrypt import AEADDecryptionResult, aead_decrypt
from ascon_hwmodel.aead import ascon_aead128_encrypt, ascon_aead128_decrypt
from ascon_hwmodel.rate import rate_bytes_from_state, replace_rate_bytes, xor_rate_bytes

# NIST hash/XOF byte-oriented model
from ascon_hwmodel.hash_xof import HashXofConfig, HashXofVariant, ascon_hash256, ascon_xof128, ascon_cxof128

from ascon_hwmodel.aead_stream import (
    AeadStreamKind,
    AxisAeadDecryptionResult,
    AxisAeadEncryptionResult,
    AxisStreamBeat,
    axis_aead128_decrypt,
    axis_aead128_encrypt,
    keep_mask,
    pack_axis_beats,
    unpack_axis_beats,
    valid_byte_count_from_keep,
)
