"""Generate working Ascon AEAD cores that compose a generated permutation.

The Tier-1 generator turns a generated permutation into a full authenticated-
encryption datapath by mirroring the model's config-driven reference: initialize,
absorb associated data, domain-separate, encrypt/decrypt the message, finalize,
tag. One parameterized core covers the whole AEAD family the model implements:

    variant        rate  data-rounds  key   IV
    AEAD128 (NIST)  16       p8        16B   8B
    AEAD128a        16       p8        16B   8B   (IV differs)
    Ascon-128       8        p6        16B   8B
    Ascon-80pq      8        p6        20B   4B   (160-bit key, 32-bit IV)

Key differences between variants reduce to widths and constants: rate 8 uses x0
only (rate 16 uses x0,x1); the 160-bit key is placed byte-aligned into the init
image (IV||key||nonce) and XORed before finalize relative to the last state word;
the tag is x3||x4 XOR the key's last 16 bytes. Domain separation is uniform
(x4 ^= 1<<63) across all variants, per the model.

Every variant is checked against the model in simulation (``verify.verify_aead``):
ciphertext+tag on encrypt, decrypt round-trip, and corrupted-tag rejection, over
AD/message lengths from empty through multi-block.
"""
from __future__ import annotations

# Short name -> model AEAD variant enum.
_VARIANT_ALIASES = {
    "aead128": "NIST_AEAD128",
    "aead128a": "LEGACY_ASCON128A",
    "ascon128": "LEGACY_ASCON128",
    "aead80pq": "LEGACY_ASCON80PQ",
}


def aead_variant_params(variant: str) -> dict:
    """Pull exact (rate/rounds/key/iv) params for a variant from the model."""
    from ascon_hwmodel.aead_config import AEADVariant, AEAD_CONFIGS

    enum = AEADVariant[_VARIANT_ALIASES[variant]]
    c = AEAD_CONFIGS[enum]
    return dict(
        variant=variant, enum=enum,
        rate_bytes=c.rate_bytes, intermediate_rounds=c.intermediate_rounds,
        key_bytes=c.key_bytes, iv_bytes=c.iv_bytes,
    )


def emit_aead_core(rate_bytes: int, intermediate_rounds: int, key_bytes: int, iv_bytes: bytes,
                   ad_max: int = 32, msg_max: int = 32, *, module_name: str = "ascon_aead_core") -> str:
    rate_bits = rate_bytes * 8
    key_bits = key_bytes * 8
    iv_bits = len(iv_bytes) * 8
    if iv_bits + key_bits + 128 != 320:
        raise ValueError("iv||key||nonce must be 320 bits (40 bytes)")
    admax, msgmax = int(ad_max), int(msg_max)
    adw, msgw = (admax + 16) * 8, (msgmax + 16) * 8
    iv_val = int.from_bytes(iv_bytes, "little")
    iv_lit = f"{iv_bits}'h{iv_val:0{len(iv_bytes) * 2}X}"
    data_r = "2'd1" if intermediate_rounds == 8 else "2'd0"  # p8 or p6

    init_key_mask = f"{{key_i, {320 - key_bits}'d0}}"
    final_low = 256 - key_bits
    final_key_mask = f"{{64'd0, key_i, {final_low}'d0}}" if final_low > 0 else "{64'd0, key_i}"
    tag_expr = f"{{s[319:192] ^ key_i[{key_bits - 1}:{key_bits - 128}]}}"
    ext = 320 - rate_bits  # zero-extension above the rate

    return f"""// Generated by ascon_designspace.generator.aead
// Ascon AEAD core: rate {rate_bytes}B, data rounds p{intermediate_rounds}, key
// {key_bytes}B, IV {len(iv_bytes)}B. Hardwired-FSM control, composing the
// generated ascon_perm_iter_r1 permutation core. AD <= {admax}B, message <= {msgmax}B.
module {module_name} (
  input  wire         clk,
  input  wire         rst_n,
  input  wire         start_i,
  input  wire         decrypt_i,
  input  wire [{key_bits - 1}:0] key_i,
  input  wire [127:0] nonce_i,
  input  wire [{admax * 8 - 1}:0]  ad_i,
  input  wire [7:0]   ad_len_i,
  input  wire [{msgmax * 8 - 1}:0] msg_i,
  input  wire [7:0]   msg_len_i,
  input  wire [127:0] tag_i,
  output wire [{msgmax * 8 - 1}:0] out_o,
  output reg  [127:0] tag_o,
  output reg          valid_o,
  output reg          done_o,
  output wire         busy_o
);
  localparam [3:0] S_IDLE=4'd0, S_PERM=4'd1, S_INIT_KEY=4'd2, S_AD_DECIDE=4'd3,
                   S_AD_FULL=4'd4, S_AD_PAD=4'd5, S_DOMSEP=4'd6, S_MSG_DECIDE=4'd7,
                   S_MSG_FULL=4'd8, S_MSG_PAD=4'd9, S_FIN_KEY=4'd10, S_FIN_TAG=4'd11;

  reg  [319:0] s;
  reg  [7:0]   adlen_r, msglen_r, adoff, msgoff;
  reg          dec_r;
  reg  [3:0]   st, perm_ret;
  reg  [1:0]   perm_rounds;
  reg          perm_start;
  reg  [{msgw - 1}:0] out_r;

  assign busy_o = (st != S_IDLE);
  assign out_o  = out_r[{msgmax * 8 - 1}:0];

  wire [319:0] perm_out;
  wire         perm_done;
  ascon_perm_iter_r1 u_perm (
    .clk(clk), .rst_n(rst_n), .start_i(perm_start), .rounds_i(perm_rounds),
    .state_i(s), .valid_o(perm_done), .state_o(perm_out), .busy_o()
  );

  wire [{adw - 1}:0]  adbuf  = {{128'b0, ad_i}};
  wire [{msgw - 1}:0] msgbuf = {{128'b0, msg_i}};

  wire [{rate_bits - 1}:0] ad_block  = adbuf[8*adoff  +: {rate_bits}];
  wire [{rate_bits - 1}:0] msg_block = msgbuf[8*msgoff +: {rate_bits}];
  wire [{rate_bits - 1}:0] rate      = s[{rate_bits - 1}:0];

  wire [7:0]   ad_rem  = adlen_r  - adoff;
  wire [7:0]   msg_rem = msglen_r - msgoff;
  wire [{rate_bits - 1}:0] ad_padbit  = {rate_bits}'h1 << (8*ad_rem);
  wire [{rate_bits - 1}:0] ad_mask    = ad_padbit - {rate_bits}'h1;
  wire [{rate_bits - 1}:0] msg_padbit = {rate_bits}'h1 << (8*msg_rem);
  wire [{rate_bits - 1}:0] msg_mask   = msg_padbit - {rate_bits}'h1;

  wire [{rate_bits - 1}:0] ad_padded  = (ad_block  & ad_mask)  | ad_padbit;
  wire [{rate_bits - 1}:0] msg_padded = (msg_block & msg_mask) | msg_padbit;

  wire [{rate_bits - 1}:0] full_out     = rate ^ msg_block;
  wire [{rate_bits - 1}:0] full_newrate = dec_r ? msg_block : full_out;
  wire [{rate_bits - 1}:0] pad_out      = dec_r ? (rate ^ msg_block) : (rate ^ msg_padded);
  wire [{rate_bits - 1}:0] pad_newrate  = dec_r ? (((rate & ~msg_mask) | (msg_block & msg_mask)) ^ msg_padbit)
                                    : (rate ^ msg_padded);

  wire [127:0] tag_val = {tag_expr};

  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      st <= S_IDLE; perm_start <= 1'b0; done_o <= 1'b0; valid_o <= 1'b0;
      tag_o <= 128'b0; s <= 320'b0; out_r <= {msgw}'b0;
      adlen_r <= 8'b0; msglen_r <= 8'b0; adoff <= 8'b0; msgoff <= 8'b0;
      dec_r <= 1'b0; perm_rounds <= 2'b0; perm_ret <= S_IDLE;
    end else begin
      perm_start <= 1'b0;
      case (st)
        S_IDLE:
          if (start_i) begin
            done_o   <= 1'b0;
            s        <= {{nonce_i, key_i, {iv_lit}}};
            adlen_r  <= ad_len_i;
            msglen_r <= msg_len_i;
            dec_r    <= decrypt_i;
            adoff    <= 8'b0;
            msgoff   <= 8'b0;
            out_r    <= {msgw}'b0;
            perm_rounds <= 2'd2;               // p12
            perm_ret    <= S_INIT_KEY;
            perm_start  <= 1'b1;
            st          <= S_PERM;
          end

        S_PERM:
          if (perm_done) begin
            s  <= perm_out;
            st <= perm_ret;
          end

        S_INIT_KEY: begin
          s  <= s ^ {init_key_mask};
          st <= S_AD_DECIDE;
        end

        S_AD_DECIDE:
          if (adlen_r == 8'b0) st <= S_DOMSEP;
          else if ((adlen_r - adoff) >= 8'd{rate_bytes}) st <= S_AD_FULL;
          else st <= S_AD_PAD;

        S_AD_FULL: begin
          s <= s ^ {{{ext}'b0, ad_block}};
          adoff <= adoff + 8'd{rate_bytes};
          perm_rounds <= {data_r}; perm_ret <= S_AD_DECIDE; perm_start <= 1'b1; st <= S_PERM;
        end

        S_AD_PAD: begin
          s <= s ^ {{{ext}'b0, ad_padded}};
          perm_rounds <= {data_r}; perm_ret <= S_DOMSEP; perm_start <= 1'b1; st <= S_PERM;
        end

        S_DOMSEP: begin
          s  <= s ^ {{64'h8000000000000000, 256'b0}};
          st <= S_MSG_DECIDE;
        end

        S_MSG_DECIDE:
          if (msglen_r == 8'b0) st <= S_MSG_PAD;
          else if ((msglen_r - msgoff) >= 8'd{rate_bytes}) st <= S_MSG_FULL;
          else st <= S_MSG_PAD;

        S_MSG_FULL: begin
          out_r[8*msgoff +: {rate_bits}] <= full_out;
          s <= {{s[319:{rate_bits}], full_newrate}};
          msgoff <= msgoff + 8'd{rate_bytes};
          perm_rounds <= {data_r}; perm_ret <= S_MSG_DECIDE; perm_start <= 1'b1; st <= S_PERM;
        end

        S_MSG_PAD: begin
          out_r[8*msgoff +: {rate_bits}] <= pad_out;
          s <= {{s[319:{rate_bits}], pad_newrate}};
          st <= S_FIN_KEY;
        end

        S_FIN_KEY: begin
          s <= s ^ {final_key_mask};
          perm_rounds <= 2'd2; perm_ret <= S_FIN_TAG; perm_start <= 1'b1; st <= S_PERM;
        end

        S_FIN_TAG: begin
          tag_o   <= tag_val;
          valid_o <= dec_r ? (tag_val == tag_i) : 1'b1;
          done_o  <= 1'b1;
          st      <= S_IDLE;
        end

        default: st <= S_IDLE;
      endcase
    end
  end
endmodule
"""


def emit_aead128_core(ad_max: int = 32, msg_max: int = 32, *, module_name: str = "ascon_aead128_core") -> str:
    """NIST Ascon-AEAD128 (rate 16, p8, 16B key). Thin wrapper over emit_aead_core."""
    p = aead_variant_params("aead128")
    return emit_aead_core(p["rate_bytes"], p["intermediate_rounds"], p["key_bytes"], p["iv_bytes"],
                          ad_max, msg_max, module_name=module_name)


def emit_aead_core_for(variant: str, ad_max: int = 32, msg_max: int = 32, *, module_name: str | None = None) -> str:
    p = aead_variant_params(variant)
    name = module_name or f"ascon_{variant}_core"
    return emit_aead_core(p["rate_bytes"], p["intermediate_rounds"], p["key_bytes"], p["iv_bytes"],
                          ad_max, msg_max, module_name=name)


def _hexlit(data: bytes, nbytes: int) -> str:
    val = int.from_bytes(data, "little") if data else 0
    return f"{nbytes * 8}'h{val:0{nbytes * 2}X}"


def emit_aead_testbench(vectors: list[dict], ad_max: int = 32, msg_max: int = 32, key_bytes: int = 16,
                        *, module_name: str = "ascon_aead128_core") -> str:
    """Self-checking testbench driving the AEAD core with pre-computed model vectors.
    Each vector: key, nonce, ad, msg (bytes); dec; tag_in, exp_tag (16B); exp_out
    (bytes); exp_valid; do_out, do_tag."""
    admax, msgmax = int(ad_max), int(msg_max)
    kb = int(key_bytes)
    calls = []
    for i, v in enumerate(vectors):
        calls.append(
            "    run_check({idx}, {k}, {n}, {ad}, 8'd{adl}, {msg}, 8'd{msgl}, {dec}, "
            "{tagin}, {eout}, 8'd{eoutl}, {etag}, {ev}, {dout}, {dtag});".format(
                idx=i, k=_hexlit(v["key"], kb), n=_hexlit(v["nonce"], 16),
                ad=_hexlit(v["ad"], admax), adl=len(v["ad"]),
                msg=_hexlit(v["msg"], msgmax), msgl=len(v["msg"]),
                dec="1'b1" if v["dec"] else "1'b0",
                tagin=_hexlit(v["tag_in"], 16),
                eout=_hexlit(v["exp_out"], msgmax), eoutl=len(v["exp_out"]),
                etag=_hexlit(v["exp_tag"], 16),
                ev="1'b1" if v["exp_valid"] else "1'b0",
                dout="1'b1" if v["do_out"] else "1'b0",
                dtag="1'b1" if v["do_tag"] else "1'b0",
            )
        )
    calls_txt = "\n".join(calls)
    return f"""`timescale 1ns/1ps
module tb;
  reg          clk = 1'b0, rst_n = 1'b0, start_i = 1'b0, decrypt_i = 1'b0;
  reg  [{kb * 8 - 1}:0] key_i;
  reg  [127:0] nonce_i, tag_i;
  reg  [{admax * 8 - 1}:0]  ad_i;   reg [7:0] ad_len_i;
  reg  [{msgmax * 8 - 1}:0] msg_i;  reg [7:0] msg_len_i;
  wire [{msgmax * 8 - 1}:0] out_o;
  wire [127:0] tag_o;
  wire         valid_o, done_o, busy_o;

  {module_name} dut (
    .clk(clk), .rst_n(rst_n), .start_i(start_i), .decrypt_i(decrypt_i),
    .key_i(key_i), .nonce_i(nonce_i), .ad_i(ad_i), .ad_len_i(ad_len_i),
    .msg_i(msg_i), .msg_len_i(msg_len_i), .tag_i(tag_i),
    .out_o(out_o), .tag_o(tag_o), .valid_o(valid_o), .done_o(done_o), .busy_o(busy_o)
  );

  always #5 clk = ~clk;
  integer errors = 0, trials = 0;

  task run_check;
    input integer idx;
    input [{kb * 8 - 1}:0] k;
    input [127:0] n;
    input [{admax * 8 - 1}:0] ad;  input [7:0] adl;
    input [{msgmax * 8 - 1}:0] msg; input [7:0] msgl;
    input dec;
    input [127:0] tagin;
    input [{msgmax * 8 - 1}:0] eout; input [7:0] eoutl;
    input [127:0] etag;
    input ev, do_out, do_tag;
    integer bi;
    begin
      @(negedge clk);
      key_i = k; nonce_i = n; ad_i = ad; ad_len_i = adl;
      msg_i = msg; msg_len_i = msgl; decrypt_i = dec; tag_i = tagin;
      @(negedge clk); start_i = 1'b1; @(negedge clk); start_i = 1'b0;
      wait (done_o); @(negedge clk);
      if (do_out)
        for (bi = 0; bi < eoutl; bi = bi + 1)
          if (out_o[8*bi +: 8] !== eout[8*bi +: 8]) begin
            errors = errors + 1; $display("VEC %0d OUT byte %0d got=%h exp=%h", idx, bi, out_o[8*bi +: 8], eout[8*bi +: 8]);
          end
      if (do_tag)
        if (tag_o !== etag) begin errors = errors + 1; $display("VEC %0d TAG got=%h exp=%h", idx, tag_o, etag); end
      if (valid_o !== ev) begin errors = errors + 1; $display("VEC %0d VALID got=%b exp=%b", idx, valid_o, ev); end
      trials = trials + 1;
    end
  endtask

  initial begin
    rst_n = 1'b0; repeat (3) @(negedge clk); rst_n = 1'b1; @(negedge clk);
{calls_txt}
    if (errors == 0) $display("PASS %0d trials 0 mismatches", trials);
    else             $display("FAIL %0d mismatches of %0d trials", errors, trials);
    $finish;
  end
endmodule
"""


def emit_aead128_testbench(vectors: list[dict], ad_max: int = 32, msg_max: int = 32,
                           *, module_name: str = "ascon_aead128_core") -> str:
    return emit_aead_testbench(vectors, ad_max, msg_max, key_bytes=16, module_name=module_name)
