"""Emit a microcoded-sequencer permutation core - the MICROCODED_SEQUENCER
control style from the design space, as opposed to the hardwired FSM.

Same round datapath as the iterative core (``ascon_round_const_index``, already
verified against the model), but the *control* is a microprogram: a small ROM
holds one microinstruction per round - ``{const_index, halt}`` - and a
program-counter sequencer walks it, applying the round with the ROM's constant
and stopping on the ROM's halt bit. The hardwired core instead derives the
constant and the stop condition from counter/comparator logic.

The p12 microprogram is the constant schedule 4..15; p8 and p6 are suffixes of
it (constants 8..15 and 10..15), so selecting the round count is just choosing
the ROM entry point. Because it drives the identical round function, correctness
reduces to the round function's - verified here by the standard permutation
testbench against the model's p6/p8/p12.
"""
from __future__ import annotations

from ascon_designspace.generator.permutation import emit_permutation_testbench  # re-export for callers  # noqa: F401


def emit_microcoded_permutation(*, module_name: str = "ascon_perm_microcoded") -> str:
    return f"""`include "ascon_model.vh"
// Generated by ascon_designspace.generator.control
// Microcoded-sequencer ASCON permutation. Control is a microprogram ROM walked
// by a PC; the round datapath is the verified ascon_round_const_index.
// rounds_i: 0=p6 1=p8 2=p12 (entry point into the shared p12 microprogram).
module {module_name} (
  input  wire         clk,
  input  wire         rst_n,
  input  wire         start_i,
  input  wire [1:0]   rounds_i,
  input  wire [319:0] state_i,
  output reg  [319:0] state_o,
  output reg          valid_o,
  output wire         busy_o
);
  localparam S_IDLE = 1'b0, S_RUN = 1'b1;

  // Microcode ROM: one instruction per round of p12 = {{const_index[4:0], halt}}.
  reg [4:0] ucode_const [0:11];
  reg       ucode_halt  [0:11];
  integer k;
  initial begin
    for (k = 0; k < 12; k = k + 1) begin
      ucode_const[k] = k[4:0] + 5'd4;   // p12 constant schedule: 4,5,...,15
      ucode_halt[k]  = (k == 11);        // last round halts the sequencer
    end
  end

  // Entry point into the shared program: p12 at 0, p8 at 4, p6 at 6.
  function [4:0] entry_pc;
    input [1:0] rr;
    begin
      case (rr)
        2'd0: entry_pc = 5'd6;    // p6
        2'd1: entry_pc = 5'd4;    // p8
        2'd2: entry_pc = 5'd0;    // p12
        default: entry_pc = 5'd12;
      endcase
    end
  endfunction

  reg [319:0] s;
  reg [3:0]   pc;
  reg         st;

  assign busy_o = (st != S_IDLE);

  wire [4:0]   entry      = entry_pc(rounds_i);
  wire [319:0] round_next = ascon_round_const_index(s, ucode_const[pc]);

  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      st <= S_IDLE; valid_o <= 1'b0; s <= 320'b0; state_o <= 320'b0; pc <= 4'b0;
    end else begin
      valid_o <= 1'b0;
      case (st)
        S_IDLE:
          if (start_i) begin
            s  <= state_i;
            pc <= entry[3:0];
            st <= (entry >= 5'd12) ? S_IDLE : S_RUN;
          end
        S_RUN: begin
          s <= round_next;                 // apply the round named by the ROM
          if (ucode_halt[pc]) begin
            state_o <= round_next;
            valid_o <= 1'b1;
            st      <= S_IDLE;
          end else begin
            pc <= pc + 4'd1;               // advance the microprogram counter
          end
        end
        default: st <= S_IDLE;
      endcase
    end
  end
endmodule
"""
