"""Generate working Ascon hash/XOF cores that compose a generated permutation.

Covers the sponge hash family the model implements with a callable reference:

    Hash256  - fixed 256-bit digest
    XOF128   - extendable output (word-aligned length is a generation parameter)
    CXOF128  - XOF with a customization string absorbed first

All share: rate 8 (x0), p12 throughout, 0x01 padding, and the same squeeze. XOF
differs from Hash only by IV and output length; CXOF additionally absorbs an
8-byte length word then the customization buffer before the message. Each core
composes the generated ``ascon_perm_iter_r1`` and is verified against the model
(``verify.verify_hash256`` / ``verify_xof128`` / ``verify_cxof128``).
"""
from __future__ import annotations


def _hash_iv(variant_name: str) -> int:
    from ascon_hwmodel.iv import ascon_iv
    from ascon_hwmodel.variants import AsconVariant

    return ascon_iv(AsconVariant[variant_name]).value


def _bus_bytes(byte_cap: int) -> int:
    return (byte_cap + 8) * 8


def _squeeze_states(out_words: int, data_r: str, width: int, start_id: int) -> tuple[str, str]:
    """localparam names + SQ state bodies. Between-output permutations use the
    data-phase round count (p^b); the last output does no permutation."""
    names = ", ".join(f"S_SQ{i}={width}'d{start_id + i}" for i in range(out_words))
    bodies = []
    for i in range(out_words):
        last = i == out_words - 1
        if last:
            tail = "done_o <= 1'b1;\n          st <= S_IDLE;"
        else:
            tail = f"perm_rounds <= {data_r}; perm_ret <= S_SQ{i + 1}; perm_start <= 1'b1; st <= S_PERM;"
        bodies.append(
            f"""        S_SQ{i}: begin
          digest_o[{64 * i + 63}:{64 * i}] <= s[63:0];
          {tail}
        end"""
        )
    return names, "\n".join(bodies)


def emit_hashxof_core(iv_value: int, out_words: int, msg_max: int = 32, data_rounds: int = 12, *, module_name: str) -> str:
    """Hash/XOF core (no customization). out_words * 8 bytes of output. data_rounds
    is the intermediate absorb/squeeze permutation (p^b): 12 for Hash256/XOF128,
    8 for HashA/XofA. Initialization and finalization always use p12 (p^a)."""
    msgmax = int(msg_max)
    msgw = _bus_bytes(msgmax)
    iv_lit = f"64'h{iv_value:016X}"
    outbits = out_words * 64
    data_r = "2'd1" if data_rounds == 8 else "2'd2"
    sq_names, sq_bodies = _squeeze_states(out_words, data_r, 4, 5)
    return f"""// Generated by ascon_designspace.generator.hash256
// Ascon hash/XOF core: rate 8, p12, {out_words * 8}-byte output. Composes the
// generated ascon_perm_iter_r1. Message <= {msgmax} bytes.
module {module_name} (
  input  wire         clk,
  input  wire         rst_n,
  input  wire         start_i,
  input  wire [{msgmax * 8 - 1}:0] msg_i,
  input  wire [7:0]   msg_len_i,
  output reg  [{outbits - 1}:0] digest_o,
  output reg          done_o,
  output wire         busy_o
);
  localparam [3:0] S_IDLE=4'd0, S_PERM=4'd1, S_ABS_DECIDE=4'd2, S_ABS_FULL=4'd3,
                   S_ABS_PAD=4'd4, {sq_names};

  reg  [319:0] s;
  reg  [7:0]   msglen_r, msgoff;
  reg  [3:0]   st, perm_ret;
  reg  [1:0]   perm_rounds;
  reg          perm_start;

  assign busy_o = (st != S_IDLE);

  wire [319:0] perm_out;
  wire         perm_done;
  ascon_perm_iter_r1 u_perm (
    .clk(clk), .rst_n(rst_n), .start_i(perm_start), .rounds_i(perm_rounds),
    .state_i(s), .valid_o(perm_done), .state_o(perm_out), .busy_o()
  );

  wire [{msgw - 1}:0] msgbuf = {{64'b0, msg_i}};
  wire [63:0]  blk    = msgbuf[8*msgoff +: 64];
  wire [7:0]   rem    = msglen_r - msgoff;
  wire [63:0]  padbit = 64'h1 << (8*rem);
  wire [63:0]  mask   = padbit - 64'h1;
  wire [63:0]  padded = (blk & mask) | padbit;

  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      st <= S_IDLE; perm_start <= 1'b0; done_o <= 1'b0; perm_rounds <= 2'd2;
      s <= 320'b0; digest_o <= {outbits}'b0; msglen_r <= 8'b0; msgoff <= 8'b0; perm_ret <= S_IDLE;
    end else begin
      perm_start <= 1'b0;
      case (st)
        S_IDLE:
          if (start_i) begin
            done_o   <= 1'b0;
            s        <= {{256'b0, {iv_lit}}};
            msglen_r <= msg_len_i;
            msgoff   <= 8'b0;
            perm_rounds <= 2'd2;             // init p12
            perm_ret <= S_ABS_DECIDE;
            perm_start <= 1'b1;
            st         <= S_PERM;
          end
        S_PERM:
          if (perm_done) begin s <= perm_out; st <= perm_ret; end
        S_ABS_DECIDE:
          if ((msglen_r - msgoff) >= 8'd8) st <= S_ABS_FULL;
          else st <= S_ABS_PAD;
        S_ABS_FULL: begin
          s <= s ^ {{256'b0, blk}};
          msgoff <= msgoff + 8'd8;
          perm_rounds <= {data_r}; perm_ret <= S_ABS_DECIDE; perm_start <= 1'b1; st <= S_PERM;
        end
        S_ABS_PAD: begin           // finalization permutation is always p12
          s <= s ^ {{256'b0, padded}};
          perm_rounds <= 2'd2; perm_ret <= S_SQ0; perm_start <= 1'b1; st <= S_PERM;
        end
{sq_bodies}
        default: st <= S_IDLE;
      endcase
    end
  end
endmodule
"""


def emit_hash256_core(msg_max: int = 32, *, module_name: str = "ascon_hash256_core") -> str:
    return emit_hashxof_core(_hash_iv("HASH256"), 4, msg_max, module_name=module_name)


def emit_xof128_core(out_words: int = 4, msg_max: int = 32, *, module_name: str = "ascon_xof128_core") -> str:
    return emit_hashxof_core(_hash_iv("XOF128"), out_words, msg_max, module_name=module_name)


def emit_hasha_core(msg_max: int = 32, *, module_name: str = "ascon_hasha_core") -> str:
    """Ascon-Hasha (legacy): Hash with p8 intermediate rounds (p^b=8), p12 init/final."""
    from ascon_hwmodel.hash_xof import HASH_XOF_CONFIGS, HashXofVariant

    iv = int.from_bytes(HASH_XOF_CONFIGS[HashXofVariant.LEGACY_HASHA].iv_bytes, "little")
    return emit_hashxof_core(iv, 4, msg_max, data_rounds=8, module_name=module_name)


def emit_xofa_core(out_words: int = 4, msg_max: int = 32, *, module_name: str = "ascon_xofa_core") -> str:
    """Ascon-Xofa (legacy): XOF with p8 intermediate rounds, p12 init/final."""
    from ascon_hwmodel.hash_xof import HASH_XOF_CONFIGS, HashXofVariant

    iv = int.from_bytes(HASH_XOF_CONFIGS[HashXofVariant.LEGACY_XOFA].iv_bytes, "little")
    return emit_hashxof_core(iv, out_words, msg_max, data_rounds=8, module_name=module_name)


def emit_cxof128_core(out_words: int = 4, msg_max: int = 32, cust_max: int = 32,
                      *, module_name: str = "ascon_cxof128_core") -> str:
    """CXOF128: absorb an 8-byte length word, then the customization buffer, then
    the message, then squeeze. Rate 8, p12 throughout."""
    msgmax, custmax = int(msg_max), int(cust_max)
    msgw, custw = _bus_bytes(msgmax), _bus_bytes(custmax)
    iv_lit = f"64'h{_hash_iv('CXOF128'):016X}"
    outbits = out_words * 64
    sq_names, sq_bodies = _squeeze_states(out_words, "2'd2", 5, 9)
    return f"""// Generated by ascon_designspace.generator.hash256
// Ascon-CXOF128: rate 8, p12. Absorbs len(customization) word, customization,
// then message, then squeezes {out_words * 8} bytes. Composes ascon_perm_iter_r1.
// customization <= {custmax}B, message <= {msgmax}B.
module {module_name} (
  input  wire         clk,
  input  wire         rst_n,
  input  wire         start_i,
  input  wire [{custmax * 8 - 1}:0] cust_i,
  input  wire [7:0]   cust_len_i,
  input  wire [{msgmax * 8 - 1}:0] msg_i,
  input  wire [7:0]   msg_len_i,
  output reg  [{outbits - 1}:0] digest_o,
  output reg          done_o,
  output wire         busy_o
);
  localparam [4:0] S_IDLE=5'd0, S_PERM=5'd1, S_CXLEN=5'd2,
                   S_CX_DECIDE=5'd3, S_CX_FULL=5'd4, S_CX_PAD=5'd5,
                   S_MSG_DECIDE=5'd6, S_MSG_FULL=5'd7, S_MSG_PAD=5'd8,
                   {", ".join(f"S_SQ{i}=5'd{9 + i}" for i in range(out_words))};

  reg  [319:0] s;
  reg  [7:0]   custlen_r, custoff, msglen_r, msgoff;
  reg  [4:0]   st, perm_ret;
  reg  [1:0]   perm_rounds;
  reg          perm_start;

  assign busy_o = (st != S_IDLE);

  wire [319:0] perm_out;
  wire         perm_done;
  ascon_perm_iter_r1 u_perm (
    .clk(clk), .rst_n(rst_n), .start_i(perm_start), .rounds_i(perm_rounds),
    .state_i(s), .valid_o(perm_done), .state_o(perm_out), .busy_o()
  );

  wire [{custw - 1}:0] custbuf = {{64'b0, cust_i}};
  wire [{msgw - 1}:0]  msgbuf  = {{64'b0, msg_i}};

  wire [63:0] cblk = custbuf[8*custoff +: 64];
  wire [7:0]  crem = custlen_r - custoff;
  wire [63:0] cpadbit = 64'h1 << (8*crem);
  wire [63:0] cmask   = cpadbit - 64'h1;
  wire [63:0] cpadded = (cblk & cmask) | cpadbit;

  wire [63:0] mblk = msgbuf[8*msgoff +: 64];
  wire [7:0]  mrem = msglen_r - msgoff;
  wire [63:0] mpadbit = 64'h1 << (8*mrem);
  wire [63:0] mmask   = mpadbit - 64'h1;
  wire [63:0] mpadded = (mblk & mmask) | mpadbit;

  // z0 = customization length in bits, little-endian 64-bit word.
  wire [63:0] z0 = {{cust_len_i, 3'b0}};   // cust_len_i * 8

  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      st <= S_IDLE; perm_start <= 1'b0; done_o <= 1'b0; perm_rounds <= 2'd2;
      s <= 320'b0; digest_o <= {outbits}'b0;
      custlen_r <= 8'b0; custoff <= 8'b0; msglen_r <= 8'b0; msgoff <= 8'b0; perm_ret <= S_IDLE;
    end else begin
      perm_start <= 1'b0;
      case (st)
        S_IDLE:
          if (start_i) begin
            done_o    <= 1'b0;
            s         <= {{256'b0, {iv_lit}}};
            custlen_r <= cust_len_i;
            msglen_r  <= msg_len_i;
            custoff   <= 8'b0;
            msgoff    <= 8'b0;
            perm_rounds <= 2'd2;
            perm_ret  <= S_CXLEN;
            perm_start <= 1'b1;
            st         <= S_PERM;
          end
        S_PERM:
          if (perm_done) begin s <= perm_out; st <= perm_ret; end

        S_CXLEN: begin
          s <= s ^ {{256'b0, z0}};       // absorb the length word
          perm_ret <= S_CX_DECIDE; perm_start <= 1'b1; st <= S_PERM;
        end
        S_CX_DECIDE:
          if ((custlen_r - custoff) >= 8'd8) st <= S_CX_FULL;
          else st <= S_CX_PAD;
        S_CX_FULL: begin
          s <= s ^ {{256'b0, cblk}};
          custoff <= custoff + 8'd8;
          perm_ret <= S_CX_DECIDE; perm_start <= 1'b1; st <= S_PERM;
        end
        S_CX_PAD: begin
          s <= s ^ {{256'b0, cpadded}};
          perm_ret <= S_MSG_DECIDE; perm_start <= 1'b1; st <= S_PERM;
        end

        S_MSG_DECIDE:
          if ((msglen_r - msgoff) >= 8'd8) st <= S_MSG_FULL;
          else st <= S_MSG_PAD;
        S_MSG_FULL: begin
          s <= s ^ {{256'b0, mblk}};
          msgoff <= msgoff + 8'd8;
          perm_ret <= S_MSG_DECIDE; perm_start <= 1'b1; st <= S_PERM;
        end
        S_MSG_PAD: begin
          s <= s ^ {{256'b0, mpadded}};
          perm_ret <= S_SQ0; perm_start <= 1'b1; st <= S_PERM;
        end
{sq_bodies}
        default: st <= S_IDLE;
      endcase
    end
  end
endmodule
"""


def _hexlit(data: bytes, nbytes: int) -> str:
    val = int.from_bytes(data, "little") if data else 0
    return f"{nbytes * 8}'h{val:0{nbytes * 2}X}"


def _digest_lit(digest: bytes) -> str:
    return f"{len(digest) * 8}'h{int.from_bytes(digest, 'little'):0{len(digest) * 2}X}"


def emit_hash256_testbench(vectors: list[dict], msg_max: int = 32, *, module_name: str = "ascon_hash256_core") -> str:
    return _emit_hashxof_tb(vectors, msg_max, out_bytes=32, module_name=module_name)


def emit_xof128_testbench(vectors: list[dict], out_bytes: int, msg_max: int = 32, *, module_name: str = "ascon_xof128_core") -> str:
    return _emit_hashxof_tb(vectors, msg_max, out_bytes=out_bytes, module_name=module_name)


def _emit_hashxof_tb(vectors: list[dict], msg_max: int, out_bytes: int, *, module_name: str) -> str:
    msgmax = int(msg_max)
    calls = "\n".join(
        "    run_check({idx}, {msg}, 8'd{msgl}, {dg});".format(
            idx=i, msg=_hexlit(v["msg"], msgmax), msgl=len(v["msg"]), dg=_digest_lit(v["digest"])
        )
        for i, v in enumerate(vectors)
    )
    return f"""`timescale 1ns/1ps
module tb;
  reg          clk = 1'b0, rst_n = 1'b0, start_i = 1'b0;
  reg  [{msgmax * 8 - 1}:0] msg_i;  reg [7:0] msg_len_i;
  wire [{out_bytes * 8 - 1}:0] digest_o;
  wire         done_o, busy_o;
  {module_name} dut (.clk(clk), .rst_n(rst_n), .start_i(start_i),
    .msg_i(msg_i), .msg_len_i(msg_len_i), .digest_o(digest_o), .done_o(done_o), .busy_o(busy_o));
  always #5 clk = ~clk;
  integer errors = 0, trials = 0;
  task run_check;
    input integer idx;
    input [{msgmax * 8 - 1}:0] msg; input [7:0] msgl;
    input [{out_bytes * 8 - 1}:0] expdg;
    begin
      @(negedge clk); msg_i = msg; msg_len_i = msgl;
      @(negedge clk); start_i = 1'b1; @(negedge clk); start_i = 1'b0;
      wait (done_o); @(negedge clk);
      if (digest_o !== expdg) begin errors = errors + 1; $display("VEC %0d got=%h exp=%h", idx, digest_o, expdg); end
      trials = trials + 1;
    end
  endtask
  initial begin
    rst_n = 1'b0; repeat (3) @(negedge clk); rst_n = 1'b1; @(negedge clk);
{calls}
    if (errors == 0) $display("PASS %0d trials 0 mismatches", trials);
    else             $display("FAIL %0d mismatches of %0d trials", errors, trials);
    $finish;
  end
endmodule
"""


def emit_cxof128_testbench(vectors: list[dict], out_bytes: int, msg_max: int = 32, cust_max: int = 32,
                           *, module_name: str = "ascon_cxof128_core") -> str:
    """Each vector: {cust, msg (bytes), digest (bytes)}."""
    msgmax, custmax = int(msg_max), int(cust_max)
    calls = "\n".join(
        "    run_check({idx}, {cust}, 8'd{cl}, {msg}, 8'd{ml}, {dg});".format(
            idx=i, cust=_hexlit(v["cust"], custmax), cl=len(v["cust"]),
            msg=_hexlit(v["msg"], msgmax), ml=len(v["msg"]), dg=_digest_lit(v["digest"])
        )
        for i, v in enumerate(vectors)
    )
    return f"""`timescale 1ns/1ps
module tb;
  reg          clk = 1'b0, rst_n = 1'b0, start_i = 1'b0;
  reg  [{custmax * 8 - 1}:0] cust_i; reg [7:0] cust_len_i;
  reg  [{msgmax * 8 - 1}:0] msg_i;  reg [7:0] msg_len_i;
  wire [{out_bytes * 8 - 1}:0] digest_o;
  wire         done_o, busy_o;
  {module_name} dut (.clk(clk), .rst_n(rst_n), .start_i(start_i),
    .cust_i(cust_i), .cust_len_i(cust_len_i), .msg_i(msg_i), .msg_len_i(msg_len_i),
    .digest_o(digest_o), .done_o(done_o), .busy_o(busy_o));
  always #5 clk = ~clk;
  integer errors = 0, trials = 0;
  task run_check;
    input integer idx;
    input [{custmax * 8 - 1}:0] cust; input [7:0] cl;
    input [{msgmax * 8 - 1}:0] msg; input [7:0] ml;
    input [{out_bytes * 8 - 1}:0] expdg;
    begin
      @(negedge clk); cust_i = cust; cust_len_i = cl; msg_i = msg; msg_len_i = ml;
      @(negedge clk); start_i = 1'b1; @(negedge clk); start_i = 1'b0;
      wait (done_o); @(negedge clk);
      if (digest_o !== expdg) begin errors = errors + 1; $display("VEC %0d got=%h exp=%h", idx, digest_o, expdg); end
      trials = trials + 1;
    end
  endtask
  initial begin
    rst_n = 1'b0; repeat (3) @(negedge clk); rst_n = 1'b1; @(negedge clk);
{calls}
    if (errors == 0) $display("PASS %0d trials 0 mismatches", trials);
    else             $display("FAIL %0d mismatches of %0d trials", errors, trials);
    $finish;
  end
endmodule
"""
