"""Emit a synthesizable iterative ASCON permutation, parameterized by
rounds-per-cycle.

The emitted module iterates the model's ``ascon_round_const_index`` (from
``rtl/generated/ascon_model.vh``) R rounds per clock, using the model's exact
round-constant schedule:

    p6  -> const index 10..15   (start = 16 - 6)
    p8  -> const index  8..15   (start = 16 - 8)
    p12 -> const index  4..15   (start = 16 - 12)

Per-stage guards let R not divide the round count (e.g. R=8 doing p6/p12): a
stage applies only while its index is < 16, so the final cycle does the
remainder. Result is bit-identical to applying the rounds one at a time.
"""
from __future__ import annotations

# The round-based permutation profiles this generator emits today, and the
# rounds-per-cycle each corresponds to.
ROUND_BASED_RPC: dict[str, int] = {
    "one_round_per_cycle": 1,
    "two_rounds_per_cycle": 2,
    "four_rounds_per_cycle": 4,
    "eight_rounds_per_cycle": 8,
}


def _module_name(rounds_per_cycle: int) -> str:
    return f"ascon_perm_iter_r{rounds_per_cycle}"


def emit_iterative_permutation(rounds_per_cycle: int, *, module_name: str | None = None) -> str:
    """Return synthesizable Verilog-2001 for an iterative permutation doing
    ``rounds_per_cycle`` rounds per clock."""
    r = int(rounds_per_cycle)
    if r < 1 or r > 12:
        raise ValueError("rounds_per_cycle must be in 1..12")
    name = module_name or _module_name(r)

    stages = "\n".join(
        f"      if ((idx_in + 5'd{k}) < DONE) t = ascon_round_const_index(t, (idx_in + 5'd{k})); "
        for k in range(r)
    )

    return f"""`include "ascon_model.vh"
// Generated by ascon_designspace.generator.permutation
// Iterative ASCON permutation, {r} round(s) per cycle.
// rounds_i: 0=p6 (idx 10..15), 1=p8 (8..15), 2=p12 (4..15).
module {name} (
  input  wire         clk,
  input  wire         rst_n,
  input  wire         start_i,
  input  wire [1:0]   rounds_i,
  input  wire [319:0] state_i,
  output reg  [319:0] state_o,
  output reg          valid_o,
  output wire         busy_o
);
  localparam [4:0] DONE = 5'd16;

  function [4:0] start_index;
    input [1:0] rr;
    begin
      case (rr)
        2'd0: start_index = 5'd10; // p6
        2'd1: start_index = 5'd8;  // p8
        2'd2: start_index = 5'd4;  // p12
        default: start_index = DONE;
      endcase
    end
  endfunction

  // Combinational block of up to {r} guarded rounds.
  function [319:0] r_rounds;
    input [319:0] s_in;
    input [4:0]   idx_in;
    reg   [319:0] t;
    begin
      t = s_in;
{stages}
      r_rounds = t;
    end
  endfunction

  reg [319:0] s;
  reg [4:0]   idx;
  reg         running;

  // Single combinational instance of the R-round block, shared by the state
  // update and the final-result capture (so the round logic is not duplicated).
  wire [319:0] next_s = r_rounds(s, idx);

  assign busy_o = running;

  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      running <= 1'b0;
      valid_o <= 1'b0;
      idx     <= DONE;
      s       <= 320'b0;
      state_o <= 320'b0;
    end else begin
      valid_o <= 1'b0;
      if (start_i) begin
        s       <= state_i;
        idx     <= start_index(rounds_i);
        running <= 1'b1;
      end else if (running) begin
        s <= next_s;
        if ((idx + 5'd{r}) >= DONE) begin
          state_o <= next_s;
          valid_o <= 1'b1;
          running <= 1'b0;
        end else begin
          idx <= idx + 5'd{r};
        end
      end
    end
  end
endmodule
"""


def emit_permutation_testbench(dut_module_name: str) -> str:
    """Return a self-checking testbench that compares the DUT against the model's
    NIST-verified combinational p6/p8/p12 over random and edge-case vectors.

    The DUT file supplies ``ascon_model.vh`` (unit-scope functions), so the
    testbench calls ``ascon_p6/p8/p12`` directly for the reference and does not
    re-include the model (avoiding duplicate function definitions)."""
    return f"""`timescale 1ns/1ps
module tb;
  reg          clk = 1'b0;
  reg          rst_n = 1'b0;
  reg          start = 1'b0;
  reg  [1:0]   rounds;
  reg  [319:0] st;
  wire [319:0] dut_out;
  wire         valid, busy;
  reg  [319:0] ref_out;

  {dut_module_name} dut (
    .clk(clk), .rst_n(rst_n), .start_i(start), .rounds_i(rounds),
    .state_i(st), .state_o(dut_out), .valid_o(valid), .busy_o(busy)
  );

  always #5 clk = ~clk;

  integer errors = 0;
  integer trials = 0;
  integer n, rr;

  task run_one;
    input [1:0]   rsel;
    input [319:0] s_in;
    begin
      @(negedge clk); st = s_in; rounds = rsel; start = 1'b1;
      @(negedge clk); start = 1'b0;
      while (valid !== 1'b1) @(negedge clk);
      case (rsel)
        2'd0: ref_out = ascon_p6(s_in);
        2'd1: ref_out = ascon_p8(s_in);
        default: ref_out = ascon_p12(s_in);
      endcase
      trials = trials + 1;
      if (dut_out !== ref_out) begin
        errors = errors + 1;
        $display("MISMATCH rounds=%0d", rsel);
        $display("  in =%h", s_in);
        $display("  dut=%h", dut_out);
        $display("  ref=%h", ref_out);
      end
    end
  endtask

  initial begin
    rst_n = 1'b0; repeat (3) @(negedge clk); rst_n = 1'b1;
    for (n = 0; n < 40; n = n + 1) begin
      for (rr = 0; rr < 3; rr = rr + 1) begin
        run_one(rr[1:0], {{$random,$random,$random,$random,$random,
                           $random,$random,$random,$random,$random}});
      end
    end
    // edge cases across all three round counts
    run_one(2'd0, 320'h0);
    run_one(2'd1, 320'h0);
    run_one(2'd2, 320'h0);
    run_one(2'd0, {{320{{1'b1}}}});
    run_one(2'd1, {{320{{1'b1}}}});
    run_one(2'd2, {{320{{1'b1}}}});
    if (errors == 0) $display("PASS %0d trials 0 mismatches", trials);
    else             $display("FAIL %0d mismatches of %0d trials", errors, trials);
    $finish;
  end
endmodule
"""


def _pipe_module_name(num_rounds: int) -> str:
    return f"ascon_perm_pipe_p{num_rounds}"


def emit_pipelined_permutation(num_rounds: int, *, module_name: str | None = None) -> str:
    """Return Verilog for a fully-pipelined p[num_rounds]: one round per stage,
    a register between stages, throughput one permutation per cycle after fill.

    Stage j applies round const_index (16 - num_rounds) + j, matching the model's
    schedule, so after ``num_rounds`` cycles of latency the output equals
    p[num_rounds] of the input presented ``num_rounds`` cycles earlier.
    """
    n = int(num_rounds)
    if n not in (6, 8, 12):
        raise ValueError("num_rounds must be 6, 8 or 12 (the Ascon permutation depths)")
    name = module_name or _pipe_module_name(n)
    start = 16 - n

    body = "\n".join(
        f"      stage[{j}] <= ascon_round_const_index("
        f"{'state_i' if j == 0 else f'stage[{j - 1}]'}, 4'd{start + j});\n"
        f"      vld[{j}]   <= {'valid_i' if j == 0 else f'vld[{j - 1}]'};"
        for j in range(n)
    )

    return f"""`include "ascon_model.vh"
// Generated by ascon_designspace.generator.permutation
// Fully-pipelined ASCON p[{n}] : {n} stages, one round each, 1 result/cycle.
// Latency {n} cycles; stage j does round const index {start}+j.
module {name} (
  input  wire         clk,
  input  wire         rst_n,
  input  wire         valid_i,
  input  wire [319:0] state_i,
  output wire         valid_o,
  output wire [319:0] state_o
);
  reg [319:0] stage [0:{n - 1}];
  reg [{n - 1}:0] vld;

  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      vld <= {n}'b0;
    end else begin
{body}
    end
  end

  assign state_o = stage[{n - 1}];
  assign valid_o = vld[{n - 1}];
endmodule
"""


def emit_pipeline_testbench(dut_module_name: str, num_rounds: int) -> str:
    """Self-checking testbench for a pipelined p[num_rounds]: streams random
    inputs at one/cycle and checks each output equals the model's p[num_rounds]
    of the matching input, in order (verifies correctness *and* full throughput)."""
    n = int(num_rounds)
    ref = f"ascon_p{n}"
    return f"""`timescale 1ns/1ps
module tb;
  reg          clk = 1'b0;
  reg          rst_n = 1'b0;
  reg          valid_i = 1'b0;
  reg  [319:0] state_i;
  wire         valid_o;
  wire [319:0] state_o;

  {dut_module_name} dut (
    .clk(clk), .rst_n(rst_n), .valid_i(valid_i),
    .state_i(state_i), .valid_o(valid_o), .state_o(state_o)
  );

  always #5 clk = ~clk;

  reg [319:0] inq [0:511];
  integer wr = 0, rd = 0, errors = 0, trials = 0, i;

  // Check outputs in order against the golden model.
  always @(negedge clk) begin
    if (rst_n && valid_o) begin
      if (state_o !== {ref}(inq[rd])) begin
        errors = errors + 1;
        $display("MISMATCH idx=%0d in=%h", rd, inq[rd]);
        $display("  dut=%h", state_o);
        $display("  ref=%h", {ref}(inq[rd]));
      end
      trials = trials + 1;
      rd = rd + 1;
    end
  end

  initial begin
    rst_n = 1'b0; repeat (3) @(negedge clk); rst_n = 1'b1;
    // Stream 100 inputs back to back (one per cycle) -> checks throughput=1.
    for (i = 0; i < 100; i = i + 1) begin
      @(negedge clk);
      state_i = {{$random,$random,$random,$random,$random,
                 $random,$random,$random,$random,$random}};
      valid_i = 1'b1;
      inq[wr] = state_i; wr = wr + 1;
    end
    // A couple of edge vectors.
    @(negedge clk); state_i = 320'h0;             valid_i = 1'b1; inq[wr]=state_i; wr=wr+1;
    @(negedge clk); state_i = {{320{{1'b1}}}};     valid_i = 1'b1; inq[wr]=state_i; wr=wr+1;
    @(negedge clk); valid_i = 1'b0;
    repeat ({n} + 6) @(negedge clk);
    if (errors == 0) $display("PASS %0d trials 0 mismatches", trials);
    else             $display("FAIL %0d mismatches of %0d trials", errors, trials);
    $finish;
  end
endmodule
"""
