"""Emit a column-serial ASCON permutation: process K S-box columns per cycle.

This is a genuinely area-reduced datapath (the point of the ASIC / TinyTapeout
narrow profiles), built entirely from the model's *own* emitted primitives so it
inherits their correctness:

* ``ascon_p_c``       - constant addition (one cycle per round)
* ``ascon_sbox5_lut`` - the exact 5-bit S-box, applied to K columns per cycle
* ``ascon_p_l``       - linear diffusion (one cycle per round)

Column j is bit j of each 64-bit word: {x0[j], x1[j], x2[j], x3[j], x4[j]} =
{s[j], s[64+j], s[128+j], s[192+j], s[256+j]}, exactly the layout the model's
``ascon_p_s_lut`` uses. Only the S-box layer is serialized; p_c and p_l are
full-width single-cycle steps. A round therefore takes 2 + ceil(64/K) cycles.

The module presents the *same* interface as the iterative core
(``start_i``/``rounds_i``/``state_o``/``valid_o``/``busy_o``), so the standard
permutation testbench verifies it against the golden model unchanged.
"""
from __future__ import annotations

# The column-serial profile in the design space processes one column per cycle
# (sbox_columns_per_cycle = 1); the generator supports wider chunks too.
COLUMN_SERIAL_COLUMNS = (1, 2, 4, 8)


def _module_name(columns_per_cycle: int) -> str:
    return f"ascon_perm_colser_k{columns_per_cycle}"


def _sbox_chunk_body(k: int) -> str:
    blocks = []
    for m in range(k):
        blocks.append(
            f"      j = base + 7'd{m};\n"
            f"      if (j < 7'd64) begin\n"
            f"        y = ascon_sbox5_lut({{o[j], o[64+j], o[128+j], o[192+j], o[256+j]}});\n"
            f"        o[j]       = y[4];\n"
            f"        o[64+j]    = y[3];\n"
            f"        o[128+j]   = y[2];\n"
            f"        o[192+j]   = y[1];\n"
            f"        o[256+j]   = y[0];\n"
            f"      end"
        )
    return "\n".join(blocks)


def emit_column_serial_permutation(columns_per_cycle: int, *, module_name: str | None = None) -> str:
    k = int(columns_per_cycle)
    if k not in (1, 2, 4, 8, 16, 32):
        raise ValueError("columns_per_cycle must divide 64 (1, 2, 4, 8, 16 or 32)")
    name = module_name or _module_name(k)
    return f"""`include "ascon_model.vh"
// Generated by ascon_designspace.generator.serial
// Column-serial ASCON permutation: {k} S-box column(s) per cycle.
// Round = 2 + ceil(64/{k}) cycles (p_c, serial p_s, p_l). rounds_i: 0=p6 1=p8 2=p12.
module {name} (
  input  wire         clk,
  input  wire         rst_n,
  input  wire         start_i,
  input  wire [1:0]   rounds_i,
  input  wire [319:0] state_i,
  output reg  [319:0] state_o,
  output reg          valid_o,
  output wire         busy_o
);
  localparam [4:0] DONE = 5'd16;
  localparam [2:0] S_IDLE = 3'd0, S_PC = 3'd1, S_SBOX = 3'd2, S_LIN = 3'd3;

  function [4:0] start_index;
    input [1:0] rr;
    begin
      case (rr)
        2'd0: start_index = 5'd10;
        2'd1: start_index = 5'd8;
        2'd2: start_index = 5'd4;
        default: start_index = DONE;
      endcase
    end
  endfunction

  // Apply {k} S-box column(s) starting at `base`, writing back; rest unchanged.
  function [319:0] sbox_chunk;
    input [319:0] s_in;
    input [6:0]   base;
    reg   [319:0] o;
    reg   [4:0]   y;
    reg   [6:0]   j;
    begin
      o = s_in;
{_sbox_chunk_body(k)}
      sbox_chunk = o;
    end
  endfunction

  reg [319:0] s;
  reg [4:0]   idx;
  reg [6:0]   col;
  reg [2:0]   st;

  assign busy_o = (st != S_IDLE);

  wire [319:0] lin_next = ascon_p_l(s);

  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      st      <= S_IDLE;
      valid_o <= 1'b0;
      idx     <= DONE;
      col     <= 7'd0;
      s       <= 320'b0;
      state_o <= 320'b0;
    end else begin
      valid_o <= 1'b0;
      case (st)
        S_IDLE:
          if (start_i) begin
            s   <= state_i;
            idx <= start_index(rounds_i);
            col <= 7'd0;
            st  <= (start_index(rounds_i) >= DONE) ? S_IDLE : S_PC;
          end
        S_PC: begin
          s   <= ascon_p_c(s, idx[3:0]);
          col <= 7'd0;
          st  <= S_SBOX;
        end
        S_SBOX: begin
          s <= sbox_chunk(s, col);
          if (col + 7'd{k} >= 7'd64) st <= S_LIN;
          else col <= col + 7'd{k};
        end
        S_LIN: begin
          s <= lin_next;
          if (idx + 5'd1 >= DONE) begin
            state_o <= lin_next;
            valid_o <= 1'b1;
            st      <= S_IDLE;
          end else begin
            idx <= idx + 5'd1;
            st  <= S_PC;
          end
        end
        default: st <= S_IDLE;
      endcase
    end
  end
endmodule
"""


def emit_bit_serial_permutation(*, module_name: str = "ascon_perm_bitser") -> str:
    """Return Verilog for a bit-serial ASCON permutation.

    The most-serial datapath the generator emits: both layers are serialized.

    * substitution: one 5-bit S-box column per cycle (the S-box's atomic unit;
      a sub-column datapath is impossible since the S-box needs all 5 column
      bits at once), applied in place - 64 cycles.
    * linear diffusion: one bit *per word* per cycle. Each output bit is
      x_i[j] ^ x_i[(j+r1)%64] ^ x_i[(j+r2)%64]; because 64 = 2**6 the rotated
      index is just a truncated 6-bit add. Computed into a working register so
      the pre-update word survives, then swapped - 64 cycles.

    So the combinational core is one S-box plus five 3-input XORs; everything
    else is registers. A round is 2 + 64 + 64 cycles. Same interface as the
    iterative core, so the standard permutation testbench verifies it against
    the model's p6/p8/p12.
    """
    # ASCON linear-layer rotation constants (x0..x4), matching ascon_p_l.
    rot = [(19, 28), (61, 39), (1, 6), (10, 17), (7, 41)]
    lin = []
    for i, (r1, r2) in enumerate(rot):
        b = i * 64
        base = "" if b == 0 else f"{b} + "
        lin.append(
            f"          t[{base}j6] <= s[{base}j6]"
            f" ^ s[{base}((j6 + 6'd{r1}) & 6'h3F)]"
            f" ^ s[{base}((j6 + 6'd{r2}) & 6'h3F)];"
        )
    lin_body = "\n".join(lin)

    return f"""`include "ascon_model.vh"
// Generated by ascon_designspace.generator.serial
// Bit-serial ASCON permutation: serial S-box (1 column/cycle) AND serial linear
// layer (1 bit/word/cycle). Round = 2 + 64 + 64 cycles. rounds_i: 0=p6 1=p8 2=p12.
module {module_name} (
  input  wire         clk,
  input  wire         rst_n,
  input  wire         start_i,
  input  wire [1:0]   rounds_i,
  input  wire [319:0] state_i,
  output reg  [319:0] state_o,
  output reg          valid_o,
  output wire         busy_o
);
  localparam [4:0] DONE = 5'd16;
  localparam [2:0] S_IDLE = 3'd0, S_PC = 3'd1, S_SBOX = 3'd2, S_LIN = 3'd3, S_LSWAP = 3'd4;

  function [4:0] start_index;
    input [1:0] rr;
    begin
      case (rr)
        2'd0: start_index = 5'd10;
        2'd1: start_index = 5'd8;
        2'd2: start_index = 5'd4;
        default: start_index = DONE;
      endcase
    end
  endfunction

  reg [319:0] s, t;
  reg [4:0]   idx;
  reg [6:0]   j;
  reg [2:0]   st;
  wire [5:0]  j6 = j[5:0];

  assign busy_o = (st != S_IDLE);

  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      st <= S_IDLE; valid_o <= 1'b0; idx <= DONE; j <= 7'd0;
      s <= 320'b0; t <= 320'b0; state_o <= 320'b0;
    end else begin
      valid_o <= 1'b0;
      case (st)
        S_IDLE:
          if (start_i) begin
            s   <= state_i;
            idx <= start_index(rounds_i);
            j   <= 7'd0;
            st  <= (start_index(rounds_i) >= DONE) ? S_IDLE : S_PC;
          end
        S_PC: begin
          s  <= ascon_p_c(s, idx[3:0]);
          j  <= 7'd0;
          st <= S_SBOX;
        end
        S_SBOX: begin : sbox_blk
          reg [4:0] yv;
          yv = ascon_sbox5_lut({{s[j6], s[64+j6], s[128+j6], s[192+j6], s[256+j6]}});
          s[      j6] <= yv[4];
          s[ 64 + j6] <= yv[3];
          s[128 + j6] <= yv[2];
          s[192 + j6] <= yv[1];
          s[256 + j6] <= yv[0];
          if (j == 7'd63) begin j <= 7'd0; st <= S_LIN; end
          else j <= j + 7'd1;
        end
        S_LIN: begin
{lin_body}
          if (j == 7'd63) begin j <= 7'd0; st <= S_LSWAP; end
          else j <= j + 7'd1;
        end
        S_LSWAP: begin
          s <= t;
          if (idx + 5'd1 >= DONE) begin
            state_o <= t;
            valid_o <= 1'b1;
            st      <= S_IDLE;
          end else begin
            idx <= idx + 5'd1;
            j   <= 7'd0;
            st  <= S_PC;
          end
        end
        default: st <= S_IDLE;
      endcase
    end
  end
endmodule
"""
