"""Emit a self-checking board "smoke" top around a generated permutation core.

The top runs the generated core on a fixed input, computes p12, and compares the
result to the golden value from the reference model (embedded at generation
time, so the board itself checks the generated hardware). It targets a board
with six active-low LEDs (e.g. Tang Nano 9K):

    led[0]  : heartbeat (alive)
    led[1]  : result matches golden p12   (lit = correct)
    led[2]  : computation finished
    led[5:3]: off

This is the artifact that ties the generator (3a) to the board flow (3b): the
thing that gets synthesized and flashed is generated RTL, checked end to end.
"""
from __future__ import annotations


def golden_p12_hex(input_int: int = 0) -> str:
    """Golden p12 of ``input_int`` as an 80-hex-digit (320-bit) string, computed
    by the reference model (same bit convention as the emitted Verilog)."""
    from ascon_hwmodel.p12 import ascon_p12
    from ascon_hwmodel.state import AsconState

    return format(ascon_p12(AsconState.from_int(input_int)).to_int(), "080x")


def emit_perm_smoke_top(
    rounds_per_cycle: int,
    *,
    input_int: int = 0,
    top_name: str = "tangnano9k_perm_smoke",
    internal_reset: bool = False,
) -> str:
    """Verilog for a self-checking smoke top instantiating ``ascon_perm_iter_r<R>``.

    The core module itself is emitted separately (see
    ``generator.permutation.emit_iterative_permutation``); the build lists both
    files. This top does not ``include`` the core, so the model functions are
    defined exactly once (by the core file).

    With ``internal_reset=True`` the top has only ``clk`` and ``led`` ports and
    derives its reset from a power-on counter - useful for boards (like the Tang
    Nano 20K) where no reset button pin is wired."""
    core = f"ascon_perm_iter_r{int(rounds_per_cycle)}"
    golden = golden_p12_hex(input_int)
    inp = format(int(input_int), "080x")
    if internal_reset:
        ports = "  input  wire       clk,\n  output wire [5:0] led"
        reset_gen = (
            "\n  // Internal power-on reset: hold rst_n low for the first 16 cycles.\n"
            "  reg [3:0] por = 4'b0;\n"
            "  wire      rst_n = &por;\n"
            "  always @(posedge clk) if (!(&por)) por <= por + 4'b1;\n"
        )
    else:
        ports = "  input  wire       clk,\n  input  wire       rst_n,\n  output wire [5:0] led"
        reset_gen = ""
    return f"""// Generated by ascon_designspace.generator.smoke
// Self-checking smoke top: runs the generated core {core} (p12) and lights an
// LED if the result matches the reference model's golden value.
module {top_name} (
{ports}
);
  localparam [319:0] INPUT_VEC  = 320'h{inp};
  localparam [319:0] GOLDEN_P12 = 320'h{golden};
{reset_gen}

  reg          start;
  reg          started;
  wire [319:0] result;
  wire         valid, busy;

  {core} u_perm (
    .clk(clk), .rst_n(rst_n),
    .start_i(start), .rounds_i(2'd2),   // 2 = p12
    .state_i(INPUT_VEC),
    .state_o(result), .valid_o(valid), .busy_o(busy)
  );

  // Kick off exactly once after reset is released.
  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      start   <= 1'b0;
      started <= 1'b0;
    end else begin
      start <= 1'b0;
      if (!started) begin
        start   <= 1'b1;
        started <= 1'b1;
      end
    end
  end

  reg match, done_seen;
  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      match     <= 1'b0;
      done_seen <= 1'b0;
    end else if (valid) begin
      match     <= (result == GOLDEN_P12);
      done_seen <= 1'b1;
    end
  end

  reg [23:0] hb;
  always @(posedge clk or negedge rst_n)
    if (!rst_n) hb <= 24'b0;
    else        hb <= hb + 24'b1;

  // Active-low LEDs: drive 0 to light.
  assign led[0]   = ~hb[23];      // heartbeat blink
  assign led[1]   = ~match;       // lit when result is correct
  assign led[2]   = ~done_seen;   // lit when finished
  assign led[5:3] = 3'b111;       // off
endmodule
"""
