rtl/common/ascon_accel_regs.vh
rtl/common/ascon_accel_axis_defs.vh
rtl/common/ascon_round_comb.v
rtl/common/ascon_accel_mmio_regs.v
rtl/stream/ascon_aead128_stream_encrypt.v
rtl/stream/ascon_aead128_stream_decrypt_buffered.v
rtl/stream/ascon_aead128_stream.v
rtl/common/ascon_accel_stream_aead128_top.v
rtl/common/ascon_axis_mmio_bridge.v
rtl/common/ascon_accel_stream_aead128_axis_mmio_system.v
