"""Emit an AXI-Stream Ascon-AEAD128 accelerator.

Two layers live here:

* ``emit_aead128_axis`` - the stream-native engine. Config (key, nonce,
  lengths, decrypt, expected tag) is latched on ``start_i``; associated data
  then message bytes arrive on an AXI-Stream slave port (``s_tuser`` selects
  AD=0 / message=1, ``s_tkeep`` marks valid bytes, ``s_tlast`` ends each
  segment); ciphertext/plaintext leaves on an AXI-Stream master port; the tag
  and validity are registered outputs. Internally it wraps the model-verified
  ``ascon_aead128_core`` (bounded to AD_MAX/MSG_MAX bytes).

* ``emit_aead128_axis_mmio`` (below) - a memory-mapped peripheral that bridges
  the firmware driver's exact register map to that engine, so the existing
  benchmark firmware drives it unchanged.

Both are plain Verilog (yosys-friendly) and verified in simulation against the
NIST-verified model - see ``generator.verify.verify_aead128_axis`` /
``verify_aead128_axis_mmio``.
"""
from __future__ import annotations


def emit_aead128_axis(ad_max: int = 32, msg_max: int = 32, *, module_name: str = "ascon_aead128_axis") -> str:
    admax = int(ad_max)
    msgmax = int(msg_max)
    return f"""// Generated by ascon_designspace.generator.axis
// Stream-native Ascon-AEAD128 accelerator. Wraps the verified ascon_aead128_core.
module {module_name} #(
  parameter AD_MAX  = {admax},
  parameter MSG_MAX = {msgmax}
) (
  input  wire         clk,
  input  wire         rst_n,
  input  wire         start_i,
  input  wire         decrypt_i,
  input  wire [127:0] key_i,
  input  wire [127:0] nonce_i,
  input  wire [7:0]   ad_len_i,
  input  wire [7:0]   msg_len_i,
  input  wire [127:0] tag_i,
  // AXI-Stream slave: AD bytes (s_tuser=0) then message bytes (s_tuser=1)
  input  wire [31:0]  s_tdata,
  input  wire [3:0]   s_tkeep,
  input  wire         s_tuser,
  input  wire         s_tlast,
  input  wire         s_tvalid,
  output wire         s_tready,
  // AXI-Stream master: ciphertext (encrypt) or plaintext (decrypt)
  output wire [31:0]  m_tdata,
  output wire [3:0]   m_tkeep,
  output wire         m_tlast,
  output wire         m_tvalid,
  input  wire         m_tready,
  // status
  output reg  [127:0] tag_o,
  output reg          valid_o,
  output reg          done_o,
  output wire         busy_o
);
  localparam [2:0] S_IDLE=3'd0, S_RX=3'd1, S_RUN=3'd2, S_BUSY=3'd6, S_WAIT=3'd3, S_TX=3'd4, S_DONE=3'd5;
  reg [2:0] st;

  reg [8*AD_MAX-1:0]  adbuf;
  reg [8*MSG_MAX-1:0] msgbuf;
  reg [8*MSG_MAX-1:0] outbuf;
  reg [7:0]   ad_pos, msg_pos, tx_pos;
  reg [7:0]   ad_len_r, msg_len_r;
  reg         decrypt_r;
  reg [127:0] key_r, nonce_r, tagin_r;

  wire [2:0] keepcnt = s_tkeep[0] + s_tkeep[1] + s_tkeep[2] + s_tkeep[3];

  assign busy_o   = (st != S_IDLE);
  assign s_tready = (st == S_RX);

  // The verified AEAD datapath.
  reg          core_start;
  wire [255:0] core_out;
  wire [127:0] core_tag;
  wire         core_valid, core_done, core_busy;
  ascon_aead128_core u_core (
    .clk(clk), .rst_n(rst_n), .start_i(core_start), .decrypt_i(decrypt_r),
    .key_i(key_r), .nonce_i(nonce_r),
    .ad_i(adbuf[255:0]), .ad_len_i(ad_len_r),
    .msg_i(msgbuf[255:0]), .msg_len_i(msg_len_r),
    .tag_i(tagin_r),
    .out_o(core_out), .tag_o(core_tag), .valid_o(core_valid),
    .done_o(core_done), .busy_o(core_busy)
  );

  // M_AXIS output framing.
  wire [7:0] rem = msg_len_r - tx_pos;   // bytes still to send
  assign m_tvalid = (st == S_TX);
  assign m_tdata  = outbuf[8*tx_pos +: 32];
  assign m_tkeep  = (rem >= 8'd4) ? 4'b1111 :
                    (rem == 8'd3) ? 4'b0111 :
                    (rem == 8'd2) ? 4'b0011 :
                    (rem == 8'd1) ? 4'b0001 : 4'b0000;
  assign m_tlast  = (st == S_TX) && (rem <= 8'd4);

  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      st <= S_IDLE; core_start <= 1'b0; done_o <= 1'b0; valid_o <= 1'b0;
      ad_pos <= 8'b0; msg_pos <= 8'b0; tx_pos <= 8'b0; tag_o <= 128'b0;
      adbuf <= {{(8*AD_MAX){{1'b0}}}}; msgbuf <= {{(8*MSG_MAX){{1'b0}}}}; outbuf <= {{(8*MSG_MAX){{1'b0}}}};
    end else begin
      core_start <= 1'b0; done_o <= 1'b0;
      case (st)
        S_IDLE: if (start_i) begin
          key_r <= key_i; nonce_r <= nonce_i; tagin_r <= tag_i;
          ad_len_r <= ad_len_i; msg_len_r <= msg_len_i; decrypt_r <= decrypt_i;
          ad_pos <= 8'b0; msg_pos <= 8'b0; tx_pos <= 8'b0; valid_o <= 1'b0;
          adbuf <= {{(8*AD_MAX){{1'b0}}}}; msgbuf <= {{(8*MSG_MAX){{1'b0}}}};
          st <= S_RX;
        end
        S_RX: if (s_tvalid) begin
          if (s_tuser == 1'b0) begin
            if (s_tkeep[0]) adbuf[8*(ad_pos+8'd0) +: 8] <= s_tdata[7:0];
            if (s_tkeep[1]) adbuf[8*(ad_pos+8'd1) +: 8] <= s_tdata[15:8];
            if (s_tkeep[2]) adbuf[8*(ad_pos+8'd2) +: 8] <= s_tdata[23:16];
            if (s_tkeep[3]) adbuf[8*(ad_pos+8'd3) +: 8] <= s_tdata[31:24];
            ad_pos <= ad_pos + keepcnt;
          end else begin
            if (s_tkeep[0]) msgbuf[8*(msg_pos+8'd0) +: 8] <= s_tdata[7:0];
            if (s_tkeep[1]) msgbuf[8*(msg_pos+8'd1) +: 8] <= s_tdata[15:8];
            if (s_tkeep[2]) msgbuf[8*(msg_pos+8'd2) +: 8] <= s_tdata[23:16];
            if (s_tkeep[3]) msgbuf[8*(msg_pos+8'd3) +: 8] <= s_tdata[31:24];
            msg_pos <= msg_pos + keepcnt;
          end
          if (s_tlast && s_tuser == 1'b1) st <= S_RUN;   // message segment ends the input
        end
        S_RUN: begin core_start <= 1'b1; st <= S_BUSY; end
        // Wait until the core actually accepts the start (busy rises) before
        // watching done_o - the core holds done_o high until the next start,
        // so catching it directly would latch the previous operation's result.
        S_BUSY: if (core_busy) st <= S_WAIT;
        S_WAIT: if (core_done) begin
          outbuf  <= core_out;
          tag_o   <= core_tag;
          valid_o <= core_valid;
          tx_pos  <= 8'b0;
          st      <= (msg_len_r == 8'd0) ? S_DONE : S_TX;
        end
        S_TX: if (m_tready) begin
          if (rem <= 8'd4) st <= S_DONE;
          else tx_pos <= tx_pos + 8'd4;
        end
        S_DONE: begin done_o <= 1'b1; st <= S_IDLE; end
        default: st <= S_IDLE;
      endcase
    end
  end
endmodule
"""


def _axis_hexlit(data: bytes, nbytes: int) -> str:
    return f"{nbytes * 8}'h{(int.from_bytes(data, 'little') if data else 0):0{nbytes * 2}X}"


def emit_aead128_axis_testbench(vectors: list[dict], ad_max: int = 32, msg_max: int = 32,
                                *, module_name: str = "ascon_aead128_axis") -> str:
    """Self-checking testbench: streams AD then message on S_AXIS, collects the
    M_AXIS output, and checks it plus the tag/valid against model vectors. Each
    vector: key, nonce, ad, inp (pt for encrypt / ct for decrypt), dec, tag_in,
    exp_out, exp_tag, exp_valid."""
    admax, msgmax = int(ad_max), int(msg_max)
    hb = _axis_hexlit
    calls = []
    for v in vectors:
        calls.append(
            "    run_vector({k},{n},{d},{ti},8'd{al},{ad},8'd{ml},{inp},{eo},{et},{ev});".format(
                k=hb(v["key"], 16), n=hb(v["nonce"], 16),
                d="1'b1" if v["dec"] else "1'b0", ti=hb(v["tag_in"], 16),
                al=len(v["ad"]), ad=hb(v["ad"], admax),
                ml=len(v["inp"]), inp=hb(v["inp"], msgmax),
                eo=hb(v["exp_out"], msgmax), et=hb(v["exp_tag"], 16),
                ev="1'b1" if v["exp_valid"] else "1'b0"))
    body = "\n".join(calls)
    return f"""`timescale 1ns/1ps
module tb;
  reg clk=1'b0, rst_n=1'b0; always #5 clk=~clk;
  reg dut_start=0, dut_decrypt=0; reg [127:0] dut_key=0, dut_nonce=0, dut_tagin=0;
  reg [7:0] dut_adlen=0, dut_msglen=0;
  reg [31:0] s_tdata=0; reg [3:0] s_tkeep=0; reg s_tuser=0, s_tlast=0, s_tvalid=0; wire s_tready;
  wire [31:0] m_tdata; wire [3:0] m_tkeep; wire m_tlast, m_tvalid; reg m_tready=0;
  wire [127:0] tag_o; wire valid_o, done_o, busy_o;

  {module_name} #(.AD_MAX({admax}), .MSG_MAX({msgmax})) dut (
    .clk(clk), .rst_n(rst_n), .start_i(dut_start), .decrypt_i(dut_decrypt),
    .key_i(dut_key), .nonce_i(dut_nonce), .ad_len_i(dut_adlen), .msg_len_i(dut_msglen), .tag_i(dut_tagin),
    .s_tdata(s_tdata), .s_tkeep(s_tkeep), .s_tuser(s_tuser), .s_tlast(s_tlast), .s_tvalid(s_tvalid), .s_tready(s_tready),
    .m_tdata(m_tdata), .m_tkeep(m_tkeep), .m_tlast(m_tlast), .m_tvalid(m_tvalid), .m_tready(m_tready),
    .tag_o(tag_o), .valid_o(valid_o), .done_o(done_o), .busy_o(busy_o));

  integer errors=0, t;

  task seg(input [7:0] len, input [{msgmax*8-1}:0] dbuf, input kind);
    integer off, i; reg [3:0] keep; reg [31:0] word; begin
      off=0;
      if (len==0) begin
        @(posedge clk); s_tdata<=0; s_tkeep<=4'b0; s_tuser<=kind; s_tlast<=1'b1; s_tvalid<=1'b1;
        @(posedge clk); while(!s_tready) @(posedge clk); s_tvalid<=1'b0; s_tlast<=1'b0;
      end else while (off<len) begin
        word=0; keep=0;
        for (i=0;i<4;i=i+1) if (off+i<len) begin word[8*i+:8]=dbuf[8*(off+i)+:8]; keep[i]=1'b1; end
        @(posedge clk); s_tdata<=word; s_tkeep<=keep; s_tuser<=kind; s_tvalid<=1'b1; s_tlast<=((off+4)>=len);
        @(posedge clk); while(!s_tready) @(posedge clk); s_tvalid<=1'b0; s_tlast<=1'b0; off=off+4;
      end
    end
  endtask

  task run_vector(input [127:0] key, input [127:0] nonce, input dec, input [127:0] tagin,
                  input [7:0] adlen, input [{admax*8-1}:0] adb,
                  input [7:0] msglen, input [{msgmax*8-1}:0] inp,
                  input [{msgmax*8-1}:0] eout, input [127:0] etag, input evalid);
    reg [{msgmax*8-1}:0] got; reg [7:0] gpos; begin
      @(posedge clk);
      dut_key<=key; dut_nonce<=nonce; dut_adlen<=adlen; dut_msglen<=msglen;
      dut_decrypt<=dec; dut_tagin<=tagin; dut_start<=1'b1;
      @(posedge clk); dut_start<=1'b0;
      seg(adlen, adb, 1'b0);
      seg(msglen, inp, 1'b1);
      got=0; gpos=0; m_tready<=1'b1;
      for (t=0; t<6000 && !done_o; t=t+1) begin
        @(posedge clk);
        if (m_tvalid) begin
          if (m_tkeep[0]) begin got[8*gpos+:8]=m_tdata[7:0];   gpos=gpos+1; end
          if (m_tkeep[1]) begin got[8*gpos+:8]=m_tdata[15:8];  gpos=gpos+1; end
          if (m_tkeep[2]) begin got[8*gpos+:8]=m_tdata[23:16]; gpos=gpos+1; end
          if (m_tkeep[3]) begin got[8*gpos+:8]=m_tdata[31:24]; gpos=gpos+1; end
        end
      end
      m_tready<=1'b0;
      if (got !== eout)     begin errors=errors+1; $display("OUT  mismatch dec=%b adlen=%0d msglen=%0d got=%h exp=%h", dec, adlen, msglen, got, eout); end
      if (!dec && tag_o !== etag) begin errors=errors+1; $display("TAG  mismatch adlen=%0d msglen=%0d got=%h exp=%h", adlen, msglen, tag_o, etag); end
      if (valid_o !== evalid) begin errors=errors+1; $display("VALID mismatch dec=%b got=%b exp=%b", dec, valid_o, evalid); end
      if (gpos !== msglen)  begin errors=errors+1; $display("LEN  mismatch got=%0d exp=%0d", gpos, msglen); end
    end
  endtask

  initial begin
    repeat(4) @(posedge clk); rst_n=1'b1; repeat(2) @(posedge clk);
{body}
    if (errors==0) $display("PASS {len(vectors)} vectors 0 mismatches");
    else $display("FAIL %0d mismatches", errors);
    $finish;
  end
endmodule
"""


def emit_aead128_axis_mmio(ad_max: int = 32, msg_max: int = 32,
                           *, module_name: str = "ascon_aead128_axis_mmio") -> str:
    """Driver-compatible MMIO peripheral around the AXI-Stream AEAD128 engine.

    Presents the firmware driver's register map on a simple synchronous register
    bus (sel/we/addr/wdata/rdata/ready - trivially adapted to NEORV32 XBUS /
    Wishbone). CONTROL.START latches config and kicks the engine; DATA_IN +
    DATA_IN_CTRL push a beat onto the engine's S_AXIS (tuser from the AD/TEXT
    bit, tkeep from the keep field, tlast from LAST); the engine's M_AXIS output
    is captured and served back through DATA_OUT/DATA_OUT_CTRL; TAG/STATUS/ERROR
    mirror the engine; a start->done cycle counter is exposed for on-chip timing.
    Verified by replaying the driver's exact register sequence against the model.
    """
    admax, msgmax = int(ad_max), int(msg_max)
    return f"""// Generated by ascon_designspace.generator.axis
// MMIO peripheral wrapping ascon_aead128_axis. Register map matches the firmware
// driver (firmware/ascon_accel/ascon_accel_regs.h).
module {module_name} #(
  parameter AD_MAX  = {admax},
  parameter MSG_MAX = {msgmax}
) (
  input  wire        clk,
  input  wire        rst_n,
  input  wire        sel,          // access strobe
  input  wire        we,           // 1 = write, 0 = read
  input  wire [7:0]  addr,         // byte offset within the peripheral window
  input  wire [31:0] wdata,
  output reg  [31:0] rdata,
  output wire        ready         // access completes this cycle when high
);
  // Register offsets.
  localparam [7:0] A_CONTROL=8'h00, A_STATUS=8'h04, A_MODE=8'h08, A_CAPS=8'h0C,
                   A_ADLEN=8'h10, A_TXTLEN=8'h14, A_OUTLEN=8'h18, A_CUSTLEN=8'h1C,
                   A_KEY0=8'h20, A_KEY1=8'h24, A_KEY2=8'h28, A_KEY3=8'h2C,
                   A_NON0=8'h30, A_NON1=8'h34, A_NON2=8'h38, A_NON3=8'h3C,
                   A_DIN=8'h40, A_DINCTL=8'h44, A_DOUT=8'h48, A_DOUTCTL=8'h4C,
                   A_TAG0=8'h60, A_TAG1=8'h64, A_TAG2=8'h68, A_TAG3=8'h6C,
                   A_CYCLO=8'h70, A_CYCHI=8'h74, A_ERR=8'h78, A_ABI=8'h7C;
  // Bit fields.
  localparam CTRL_START=32'h1, CTRL_DECRYPT=32'h2, CTRL_CLEAR=32'h100;
  localparam ST_BUSY=32'h1, ST_DONE=32'h2, ST_TAGV=32'h4, ST_ERR=32'h8, ST_INRDY=32'h10, ST_OUTV=32'h20;
  localparam D_LAST=32'h1, D_VALID=32'h2;   // in wdata ctrl: AD=1<<2, TEXT=1<<3, keep<<8
  localparam CAP=32'h0, ERR_NONE=8'd0, ERR_TAGINVALID=8'd4, ABIV=32'd1;
  localparam CAPBITS=(32'h1 | 32'h200000 | 32'h400000);  // AEAD128 | CYCLE_COUNTER | AXI_STREAM_DATA

  reg  [2:0]   mode_r;
  reg  [127:0] key_r, nonce_r, tagin_r, tag_r;
  reg  [7:0]   adlen_r, txtlen_r, outlen_r;
  reg          decrypt_r, busy_r, done_r, tagvalid_r, error_r;
  reg  [7:0]   errcode_r;
  reg  [31:0]  datain_r;
  reg  [8*MSG_MAX-1:0] outbuf;
  reg  [7:0]   out_wpos, out_rpos;
  reg  [63:0]  cyc_run, cyc_lat;
  reg          counting, start_pulse;

  // S_AXIS beat driven combinationally during a DATA_IN_CTRL write.
  wire        din_ctl_wr = sel & we & (addr == A_DINCTL);
  wire [31:0] s_tdata = datain_r;
  wire [3:0]  s_tkeep = wdata[11:8];
  wire        s_tuser = wdata[3];        // TEXT bit -> message; AD bit(1<<2) -> 0
  wire        s_tlast = wdata[0];
  wire        s_tvalid = din_ctl_wr;
  wire        s_tready;

  wire [31:0] m_tdata; wire [3:0] m_tkeep; wire m_tlast, m_tvalid;
  wire [127:0] eng_tag; wire eng_valid, eng_done, eng_busy;

  {module_name.replace('_axis_mmio','_axis') if False else 'ascon_aead128_axis'} #(.AD_MAX(AD_MAX), .MSG_MAX(MSG_MAX)) u_eng (
    .clk(clk), .rst_n(rst_n), .start_i(start_pulse), .decrypt_i(decrypt_r),
    .key_i(key_r), .nonce_i(nonce_r), .ad_len_i(adlen_r), .msg_len_i(txtlen_r), .tag_i(tagin_r),
    .s_tdata(s_tdata), .s_tkeep(s_tkeep), .s_tuser(s_tuser), .s_tlast(s_tlast),
    .s_tvalid(s_tvalid), .s_tready(s_tready),
    .m_tdata(m_tdata), .m_tkeep(m_tkeep), .m_tlast(m_tlast), .m_tvalid(m_tvalid), .m_tready(1'b1),
    .tag_o(eng_tag), .valid_o(eng_valid), .done_o(eng_done), .busy_o(eng_busy)
  );

  // A DATA_IN_CTRL write stalls until the engine accepts the beat; all else is single-cycle.
  assign ready = sel ? ((we & (addr == A_DINCTL)) ? s_tready : 1'b1) : 1'b1;

  // DATA_OUT framing for the word currently pointed at.
  wire [7:0] out_rem  = txtlen_r - out_rpos;
  wire [3:0] out_keep = (out_rem >= 8'd4) ? 4'b1111 : (out_rem == 8'd3) ? 4'b0111 :
                        (out_rem == 8'd2) ? 4'b0011 : (out_rem == 8'd1) ? 4'b0001 : 4'b0000;
  wire       out_last = (out_rem <= 8'd4);

  always @(*) begin
    case (addr)
      A_STATUS:  rdata = ST_BUSY & {{32{{busy_r}}}} | (done_r?ST_DONE:0) | (tagvalid_r?ST_TAGV:0) |
                         (error_r?ST_ERR:0) | (s_tready?ST_INRDY:0) | (done_r?ST_OUTV:0);
      A_CAPS:    rdata = CAPBITS;
      A_MODE:    rdata = {{29'b0, mode_r}};
      A_ADLEN:   rdata = {{24'b0, adlen_r}};
      A_TXTLEN:  rdata = {{24'b0, txtlen_r}};
      A_OUTLEN:  rdata = {{24'b0, outlen_r}};
      A_KEY0:    rdata = key_r[31:0];   A_KEY1: rdata = key_r[63:32];
      A_KEY2:    rdata = key_r[95:64];  A_KEY3: rdata = key_r[127:96];
      A_NON0:    rdata = nonce_r[31:0]; A_NON1: rdata = nonce_r[63:32];
      A_NON2:    rdata = nonce_r[95:64];A_NON3: rdata = nonce_r[127:96];
      A_TAG0:    rdata = tag_r[31:0];   A_TAG1: rdata = tag_r[63:32];
      A_TAG2:    rdata = tag_r[95:64];  A_TAG3: rdata = tag_r[127:96];
      A_DOUT:    rdata = outbuf[8*out_rpos +: 32];
      A_DOUTCTL: rdata = D_VALID | (out_last?D_LAST:0) | ({{28'b0, out_keep}} << 8);
      A_ERR:     rdata = {{24'b0, errcode_r}};
      A_ABI:     rdata = ABIV;
      A_CYCLO:   rdata = cyc_lat[31:0];
      A_CYCHI:   rdata = cyc_lat[63:32];
      default:   rdata = 32'b0;
    endcase
  end

  wire [2:0] mkeep = m_tkeep[0] + m_tkeep[1] + m_tkeep[2] + m_tkeep[3];

  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      mode_r<=0; key_r<=0; nonce_r<=0; tagin_r<=0; tag_r<=0;
      adlen_r<=0; txtlen_r<=0; outlen_r<=0;
      decrypt_r<=0; busy_r<=0; done_r<=0; tagvalid_r<=0; error_r<=0; errcode_r<=0;
      datain_r<=0; outbuf<=0; out_wpos<=0; out_rpos<=0;
      cyc_run<=0; cyc_lat<=0; counting<=0; start_pulse<=0;
    end else begin
      start_pulse <= 1'b0;
      if (counting) cyc_run <= cyc_run + 64'd1;

      if (eng_done) begin
        done_r <= 1'b1; tag_r <= eng_tag; busy_r <= 1'b0;
        counting <= 1'b0; cyc_lat <= cyc_run;
        if (decrypt_r && !eng_valid) begin error_r <= 1'b1; errcode_r <= ERR_TAGINVALID; tagvalid_r <= 1'b0; end
        else begin tagvalid_r <= 1'b1; errcode_r <= ERR_NONE; end
      end

      if (m_tvalid) begin
        if (m_tkeep[0]) outbuf[8*(out_wpos+8'd0) +: 8] <= m_tdata[7:0];
        if (m_tkeep[1]) outbuf[8*(out_wpos+8'd1) +: 8] <= m_tdata[15:8];
        if (m_tkeep[2]) outbuf[8*(out_wpos+8'd2) +: 8] <= m_tdata[23:16];
        if (m_tkeep[3]) outbuf[8*(out_wpos+8'd3) +: 8] <= m_tdata[31:24];
        out_wpos <= out_wpos + mkeep;
      end

      if (sel & we & ready) begin
        case (addr)
          A_MODE:   mode_r   <= wdata[2:0];
          A_ADLEN:  adlen_r  <= wdata[7:0];
          A_TXTLEN: txtlen_r <= wdata[7:0];
          A_OUTLEN: outlen_r <= wdata[7:0];
          A_KEY0: key_r[31:0]<=wdata; A_KEY1: key_r[63:32]<=wdata; A_KEY2: key_r[95:64]<=wdata; A_KEY3: key_r[127:96]<=wdata;
          A_NON0: nonce_r[31:0]<=wdata; A_NON1: nonce_r[63:32]<=wdata; A_NON2: nonce_r[95:64]<=wdata; A_NON3: nonce_r[127:96]<=wdata;
          A_TAG0: tagin_r[31:0]<=wdata; A_TAG1: tagin_r[63:32]<=wdata; A_TAG2: tagin_r[95:64]<=wdata; A_TAG3: tagin_r[127:96]<=wdata;
          A_DIN:  datain_r <= wdata;
          A_CONTROL: begin
            if (wdata & CTRL_CLEAR) begin
              busy_r<=0; done_r<=0; tagvalid_r<=0; error_r<=0; errcode_r<=0; out_wpos<=0; out_rpos<=0; counting<=0;
            end
            if (wdata & CTRL_START) begin
              decrypt_r <= (wdata & CTRL_DECRYPT) ? 1'b1 : 1'b0;
              start_pulse <= 1'b1; busy_r <= 1'b1; done_r <= 0; tagvalid_r <= 0; error_r <= 0; errcode_r <= ERR_NONE;
              out_wpos <= 0; out_rpos <= 0; cyc_run <= 0; counting <= 1'b1;
            end
          end
          default: ;
        endcase
      end

      if (sel & ~we & ready & (addr == A_DOUT)) out_rpos <= out_rpos + 8'd4;
    end
  end
endmodule
"""


def emit_aead128_axis_mmio_testbench(vectors: list[dict], ad_max: int = 32, msg_max: int = 32,
                                     *, module_name: str = "ascon_aead128_axis_mmio") -> str:
    """Driver-faithful testbench: drives the MMIO register bus through the exact
    sequence the firmware uses (CLEAR, MODE, KEY, NONCE, lengths, [TAG], START,
    stream AD, stream TEXT, poll STATUS.DONE, read DATA_OUT, read TAG, read
    ERROR) and checks output/tag/validity against model vectors."""
    admax, msgmax = int(ad_max), int(msg_max)
    hb = _axis_hexlit
    calls = []
    for v in vectors:
        calls.append(
            "    run_vec({k},{n},{d},{ti},8'd{al},{ad},8'd{ml},{inp},{eo},{et},{ev});".format(
                k=hb(v["key"], 16), n=hb(v["nonce"], 16),
                d="1'b1" if v["dec"] else "1'b0", ti=hb(v["tag_in"], 16),
                al=len(v["ad"]), ad=hb(v["ad"], admax),
                ml=len(v["inp"]), inp=hb(v["inp"], msgmax),
                eo=hb(v["exp_out"], msgmax), et=hb(v["exp_tag"], 16),
                ev="1'b1" if v["exp_valid"] else "1'b0"))
    body = "\n".join(calls)
    return f"""`timescale 1ns/1ps
module tb;
  reg clk=1'b0, rst_n=1'b0; always #5 clk=~clk;
  reg sel=0, we=0; reg [7:0] addr=0; reg [31:0] wdata=0; wire [31:0] rdata; wire ready;
  {module_name} #(.AD_MAX({admax}), .MSG_MAX({msgmax})) dut (
    .clk(clk), .rst_n(rst_n), .sel(sel), .we(we), .addr(addr), .wdata(wdata), .rdata(rdata), .ready(ready));

  localparam CTRL=8'h00, STAT=8'h04, MODE=8'h08, ADLEN=8'h10, TXTLEN=8'h14,
             K0=8'h20, K1=8'h24, K2=8'h28, K3=8'h2C, N0=8'h30, N1=8'h34, N2=8'h38, N3=8'h3C,
             DIN=8'h40, DINC=8'h44, DOUT=8'h48, DOUTC=8'h4C, T0=8'h60, T1=8'h64, T2=8'h68, T3=8'h6C, ERRR=8'h78;
  localparam [31:0] C_START=32'h1, C_DEC=32'h2, C_CLR=32'h100, S_DONE=32'h2, S_ERR=32'h8;
  localparam [31:0] D_LAST=32'h1, D_VALID=32'h2, D_AD=32'h4, D_TEXT=32'h8;
  integer errors=0;

  task bwrite(input [7:0] a, input [31:0] d); begin
    @(posedge clk); sel<=1; we<=1; addr<=a; wdata<=d;
    @(posedge clk); while(!ready) @(posedge clk); sel<=0; we<=0;
  end endtask
  task bread(input [7:0] a, output [31:0] o); begin
    @(posedge clk); sel<=1; we<=0; addr<=a;
    @(posedge clk); while(!ready) @(posedge clk); o=rdata; sel<=0;
  end endtask
  task stream(input [7:0] len, input [{msgmax*8-1}:0] dbuf, input [31:0] kind);
    integer off,i; reg [31:0] word,ctrl,keep; begin off=0;
      if (len==0) bwrite(DINC, D_VALID|D_LAST|kind);
      else while (off<len) begin
        word=0; keep=0;
        for (i=0;i<4;i=i+1) if (off+i<len) begin word[8*i+:8]=dbuf[8*(off+i)+:8]; keep=keep|(1<<i); end
        bwrite(DIN, word);
        ctrl=D_VALID|kind|(keep<<8); if (off+4>=len) ctrl=ctrl|D_LAST;
        bwrite(DINC, ctrl); off=off+4;
      end
    end endtask
  task run_vec(input [127:0] key, input [127:0] nonce, input dec, input [127:0] tagin,
               input [7:0] adlen, input [{admax*8-1}:0] adb, input [7:0] txtlen, input [{msgmax*8-1}:0] inp,
               input [{msgmax*8-1}:0] eout, input [127:0] etag, input evalid);
    reg [{msgmax*8-1}:0] got; reg [31:0] st,word,ec; integer off,i; reg [127:0] gtag; begin
      bwrite(CTRL, C_CLR); bwrite(MODE, 0);
      bwrite(K0,key[31:0]); bwrite(K1,key[63:32]); bwrite(K2,key[95:64]); bwrite(K3,key[127:96]);
      bwrite(N0,nonce[31:0]); bwrite(N1,nonce[63:32]); bwrite(N2,nonce[95:64]); bwrite(N3,nonce[127:96]);
      bwrite(ADLEN,adlen); bwrite(TXTLEN,txtlen);
      if (dec) begin bwrite(T0,tagin[31:0]); bwrite(T1,tagin[63:32]); bwrite(T2,tagin[95:64]); bwrite(T3,tagin[127:96]); end
      bwrite(CTRL, C_START | (dec?C_DEC:0));
      stream(adlen, adb, D_AD); stream(txtlen, inp, D_TEXT);
      st=0; while(!(st & S_DONE)) bread(STAT, st);
      got=0; off=0;
      while (off<txtlen) begin
        bread(DOUT, word);
        for (i=0;i<4;i=i+1) if (off<txtlen) begin got[8*off+:8]=word[8*i+:8]; off=off+1; end
        bread(DOUTC, word);
      end
      bread(T0,word); gtag[31:0]=word; bread(T1,word); gtag[63:32]=word;
      bread(T2,word); gtag[95:64]=word; bread(T3,word); gtag[127:96]=word;
      bread(ERRR, ec);
      if (got !== eout) begin errors=errors+1; $display("OUT bad dec=%b adlen=%0d txtlen=%0d got=%h exp=%h", dec,adlen,txtlen,got,eout); end
      if (!dec && gtag !== etag) begin errors=errors+1; $display("TAG bad got=%h exp=%h", gtag,etag); end
      if (dec && !evalid && !(st & S_ERR)) begin errors=errors+1; $display("expected tag-invalid error"); end
      if (dec && evalid && (st & S_ERR)) begin errors=errors+1; $display("unexpected error on valid decrypt"); end
    end endtask

  initial begin
    repeat(4) @(posedge clk); rst_n=1'b1; repeat(2) @(posedge clk);
{body}
    if (errors==0) $display("PASS {len(vectors)} vectors 0 mismatches");
    else $display("FAIL %0d mismatches", errors);
    $finish;
  end
endmodule
"""


def write_accelerator_files(out_dir) -> list:
    """Write the full AXI-Stream AEAD128 accelerator datapath (permutation, AEAD
    core, stream engine, MMIO peripheral) as Verilog files under out_dir. The
    Wishbone adapter (rtl/soc/ascon_aead128_wb.v) instantiates the MMIO module by
    name. Returns the list of written paths."""
    import pathlib

    from ascon_designspace.generator.aead import emit_aead128_core
    from ascon_designspace.generator.permutation import emit_iterative_permutation

    d = pathlib.Path(out_dir)
    d.mkdir(parents=True, exist_ok=True)
    files = {
        "ascon_perm_iter_r1.v": emit_iterative_permutation(1),
        "ascon_aead128_core.v": emit_aead128_core(),
        "ascon_aead128_axis.v": emit_aead128_axis(),
        "ascon_aead128_axis_mmio.v": emit_aead128_axis_mmio(),
    }
    written = []
    for name, text in files.items():
        (d / name).write_text(text)
        written.append(str(d / name))
    return written


def emit_aead128_wb_xbus_testbench(vectors: list[dict], ad_max: int = 32, msg_max: int = 32) -> str:
    """Testbench that drives the ascon_aead128_wb adapter the way NEORV32's XBUS
    does - STB as a single-cycle pulse, CYC held until ACK, ACK/read-data sampled
    on the ack cycle - and replays the firmware driver's register protocol,
    checking output/tag/validity against model vectors."""
    hb = _axis_hexlit
    calls = []
    for v in vectors:
        calls.append(
            "    run_vec({k},{n},{d},{ti},8'd{al},{ad},8'd{ml},{inp},{eo},{et},{ev});".format(
                k=hb(v["key"], 16), n=hb(v["nonce"], 16),
                d="1'b1" if v["dec"] else "1'b0", ti=hb(v["tag_in"], 16),
                al=len(v["ad"]), ad=hb(v["ad"], ad_max),
                ml=len(v["inp"]), inp=hb(v["inp"], msg_max),
                eo=hb(v["exp_out"], msg_max), et=hb(v["exp_tag"], 16),
                ev="1'b1" if v["exp_valid"] else "1'b0"))
    body = "\n".join(calls)
    return f"""`timescale 1ns/1ps
module tb;
  reg clk=0, rst_n=0; always #5 clk=~clk;
  reg wb_stb=0, wb_cyc=0, wb_we=0; reg [31:0] wb_adr=0, wb_wdat=0;
  wire [31:0] wb_rdat; wire wb_ack, wb_err;
  ascon_aead128_wb dut (.clk(clk), .rst_n(rst_n), .wb_adr_i(wb_adr), .wb_dat_i(wb_wdat),
    .wb_dat_o(wb_rdat), .wb_we_i(wb_we), .wb_sel_i(4'hf), .wb_stb_i(wb_stb), .wb_cyc_i(wb_cyc),
    .wb_ack_o(wb_ack), .wb_err_o(wb_err));
  localparam CTRL=8'h00, STAT=8'h04, MODE=8'h08, ADLEN=8'h10, TXTLEN=8'h14,
             K0=8'h20, K1=8'h24, K2=8'h28, K3=8'h2C, N0=8'h30, N1=8'h34, N2=8'h38, N3=8'h3C,
             DIN=8'h40, DINC=8'h44, DOUT=8'h48, DOUTC=8'h4C, T0=8'h60, T1=8'h64, T2=8'h68, T3=8'h6C, ERRR=8'h78;
  localparam [31:0] C_START=32'h1, C_DEC=32'h2, C_CLR=32'h100, S_DONE=32'h2, S_ERR=32'h8;
  localparam [31:0] D_LAST=32'h1, D_VALID=32'h2, D_AD=32'h4, D_TEXT=32'h8;
  integer errors=0, guard;

  task xfer(input we_i, input [7:0] a, input [31:0] wd, output [31:0] rdo);
    begin
      @(posedge clk); wb_cyc<=1; wb_stb<=1; wb_we<=we_i; wb_adr<={{24'b0, a}}; wb_wdat<=wd;
      @(posedge clk); wb_stb<=0;                       // strobe is a single-cycle pulse
      guard=0;
      while (!wb_ack && guard<100000) begin @(posedge clk); guard=guard+1; end
      rdo = wb_rdat;
      if (!wb_ack) begin errors=errors+1; $display("XBUS TIMEOUT addr=%0h we=%b", a, we_i); end
      wb_cyc<=0; wb_we<=0; @(posedge clk);
    end endtask
  task wr(input [7:0] a, input [31:0] d); reg [31:0] j; begin xfer(1'b1,a,d,j); end endtask
  task rd(input [7:0] a, output [31:0] o); begin xfer(1'b0,a,32'b0,o); end endtask
  task stream(input [7:0] len, input [{msg_max*8-1}:0] dbuf, input [31:0] kind);
    integer off,i; reg [31:0] word,ctrl,keep; begin off=0;
      if (len==0) wr(DINC, D_VALID|D_LAST|kind);
      else while (off<len) begin word=0; keep=0;
        for (i=0;i<4;i=i+1) if (off+i<len) begin word[8*i+:8]=dbuf[8*(off+i)+:8]; keep=keep|(1<<i); end
        wr(DIN, word); ctrl=D_VALID|kind|(keep<<8); if (off+4>=len) ctrl=ctrl|D_LAST;
        wr(DINC, ctrl); off=off+4; end
    end endtask
  task run_vec(input [127:0] key, input [127:0] nonce, input dec, input [127:0] tagin,
               input [7:0] adlen, input [{ad_max*8-1}:0] adb, input [7:0] txtlen, input [{msg_max*8-1}:0] inp,
               input [{msg_max*8-1}:0] eout, input [127:0] etag, input evalid);
    reg [{msg_max*8-1}:0] got; reg [31:0] st,word,ec; integer off,i; reg [127:0] gtag; begin
      wr(CTRL,C_CLR); wr(MODE,0);
      wr(K0,key[31:0]); wr(K1,key[63:32]); wr(K2,key[95:64]); wr(K3,key[127:96]);
      wr(N0,nonce[31:0]); wr(N1,nonce[63:32]); wr(N2,nonce[95:64]); wr(N3,nonce[127:96]);
      wr(ADLEN,adlen); wr(TXTLEN,txtlen);
      if (dec) begin wr(T0,tagin[31:0]); wr(T1,tagin[63:32]); wr(T2,tagin[95:64]); wr(T3,tagin[127:96]); end
      wr(CTRL, C_START | (dec?C_DEC:0));
      stream(adlen,adb,D_AD); stream(txtlen,inp,D_TEXT);
      st=0; guard=0; while(!(st&S_DONE) && guard<100000) begin rd(STAT,st); guard=guard+1; end
      got=0; off=0;
      while (off<txtlen) begin rd(DOUT,word);
        for (i=0;i<4;i=i+1) if (off<txtlen) begin got[8*off+:8]=word[8*i+:8]; off=off+1; end
        rd(DOUTC,word); end
      rd(T0,word);gtag[31:0]=word; rd(T1,word);gtag[63:32]=word; rd(T2,word);gtag[95:64]=word; rd(T3,word);gtag[127:96]=word;
      rd(ERRR,ec);
      if (got !== eout) begin errors=errors+1; $display("OUT bad dec=%b al=%0d ml=%0d got=%h exp=%h",dec,adlen,txtlen,got,eout); end
      if (!dec && gtag !== etag) begin errors=errors+1; $display("TAG bad got=%h exp=%h",gtag,etag); end
      if (dec && !evalid && !(st&S_ERR)) begin errors=errors+1; $display("expected tag-invalid"); end
    end endtask

  initial begin
    repeat(4) @(posedge clk); rst_n=1; repeat(2) @(posedge clk);
{body}
    if (errors==0) $display("PASS {len(vectors)} vectors 0 mismatches");
    else $display("FAIL %0d mismatches", errors);
    $finish;
  end
endmodule
"""
