"""Structural wrappers that arrange generated permutation cores into the
design-space *topologies*, rather than changing the permutation datapath itself.

Today this emits the ONE_PIPELINED_PERMUTATION_N_CONTEXTS topology: a single
fully-pipelined permutation core (the throughput-verified one from
``permutation.py``) with N independent contexts interleaved through it. Because
the pipeline accepts one input per cycle and has fixed latency, up to N distinct
sessions can be in flight at once; a small tag pipeline carries each input's
context id in lockstep so results come out labelled. This is the hardwired-FSM /
single-shared-pipeline arrangement the catalog calls out for keeping a pipelined
core busy across contexts.

The wrapper composes the verified core unchanged, so its correctness reduces to
the core's (already proven bit-exact vs the model) plus the tag alignment, which
the testbench checks by tagging every input and verifying each labelled output.
"""
from __future__ import annotations

import math


def _ctx_width(num_contexts: int) -> int:
    return max(1, math.ceil(math.log2(num_contexts)))


def context_pipeline_name(num_rounds: int, num_contexts: int) -> str:
    return f"ascon_ctx_pipe_p{num_rounds}_c{num_contexts}"


def emit_context_pipeline(num_rounds: int, num_contexts: int, *, module_name: str | None = None) -> str:
    """Wrapper module for N contexts through one pipelined p[num_rounds].

    Emits only the wrapper; instantiate alongside ``emit_pipelined_permutation``
    (which supplies the ``ascon_perm_pipe_p{N}`` core and the model include)."""
    n = int(num_rounds)
    c = int(num_contexts)
    if n not in (6, 8, 12):
        raise ValueError("num_rounds must be 6, 8 or 12")
    if c < 2:
        raise ValueError("num_contexts must be >= 2 (that is the point of interleaving)")
    name = module_name or context_pipeline_name(n, c)
    w = _ctx_width(c)
    core = f"ascon_perm_pipe_p{n}"
    return f"""// Generated by ascon_designspace.generator.structural
// ONE_PIPELINED_PERMUTATION_N_CONTEXTS: {c} contexts interleaved through one
// pipelined p[{n}] core (latency {n}, one result/cycle). ctx_i tags each input;
// ctx_o labels each result. Compose with {core} (from emit_pipelined_permutation).
module {name} (
  input  wire         clk,
  input  wire         rst_n,
  input  wire         valid_i,
  input  wire [{w - 1}:0]   ctx_i,
  input  wire [319:0] state_i,
  output wire         valid_o,
  output wire [{w - 1}:0]   ctx_o,
  output wire [319:0] state_o
);
  // Data path: the throughput-verified pipelined permutation, composed as-is.
  {core} u_perm (
    .clk(clk), .rst_n(rst_n), .valid_i(valid_i),
    .state_i(state_i), .valid_o(valid_o), .state_o(state_o)
  );

  // Tag path: carry the context id through {n} stages in lockstep with the data
  // pipeline, so ctx_o lines up with state_o.
  reg [{w - 1}:0] ctx_stage [0:{n - 1}];
  integer k;
  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      for (k = 0; k < {n}; k = k + 1) ctx_stage[k] <= {w}'b0;
    end else begin
      ctx_stage[0] <= ctx_i;
      for (k = 1; k < {n}; k = k + 1) ctx_stage[k] <= ctx_stage[k - 1];
    end
  end

  assign ctx_o = ctx_stage[{n - 1}];
endmodule
"""


def emit_context_pipeline_testbench(num_rounds: int, num_contexts: int, *, module_name: str | None = None) -> str:
    """Self-checking testbench: round-robins {C} contexts through the wrapper at
    one input/cycle, and checks each labelled output is p[N] of the state that
    entered with that context id, in order."""
    n = int(num_rounds)
    c = int(num_contexts)
    name = module_name or context_pipeline_name(n, c)
    w = _ctx_width(c)
    ref = f"ascon_p{n}"
    return f"""`timescale 1ns/1ps
module tb;
  reg          clk = 1'b0;
  reg          rst_n = 1'b0;
  reg          valid_i = 1'b0;
  reg  [{w - 1}:0]   ctx_i;
  reg  [319:0] state_i;
  wire         valid_o;
  wire [{w - 1}:0]   ctx_o;
  wire [319:0] state_o;

  {name} dut (
    .clk(clk), .rst_n(rst_n), .valid_i(valid_i),
    .ctx_i(ctx_i), .state_i(state_i),
    .valid_o(valid_o), .ctx_o(ctx_o), .state_o(state_o)
  );

  always #5 clk = ~clk;

  reg [319:0] inq  [0:511];
  reg [{w - 1}:0]  ctxq [0:511];
  integer wr = 0, rd = 0, errors = 0, trials = 0, i;

  always @(negedge clk) begin
    if (rst_n && valid_o) begin
      if (state_o !== {ref}(inq[rd])) begin
        errors = errors + 1;
        $display("DATA MISMATCH idx=%0d ctx=%0d", rd, ctx_o);
      end
      if (ctx_o !== ctxq[rd]) begin
        errors = errors + 1;
        $display("CTX MISMATCH idx=%0d got=%0d exp=%0d", rd, ctx_o, ctxq[rd]);
      end
      trials = trials + 1;
      rd = rd + 1;
    end
  end

  initial begin
    rst_n = 1'b0; repeat (3) @(negedge clk); rst_n = 1'b1;
    for (i = 0; i < 120; i = i + 1) begin
      @(negedge clk);
      state_i = {{$random,$random,$random,$random,$random,
                 $random,$random,$random,$random,$random}};
      ctx_i   = i % {c};                 // round-robin the {c} contexts
      valid_i = 1'b1;
      inq[wr] = state_i; ctxq[wr] = ctx_i; wr = wr + 1;
    end
    @(negedge clk); valid_i = 1'b0;
    repeat ({n} + 6) @(negedge clk);
    if (errors == 0) $display("PASS %0d trials 0 mismatches", trials);
    else             $display("FAIL %0d mismatches of %0d trials", errors, trials);
    $finish;
  end
endmodule
"""


def multi_pipeline_name(num_rounds: int, num_pipelines: int, num_contexts: int) -> str:
    return f"ascon_mpipe_p{num_rounds}_m{num_pipelines}_c{num_contexts}"


def emit_multi_pipeline(num_rounds: int, num_pipelines: int, num_contexts: int, *, module_name: str | None = None) -> str:
    """M_PIPELINES_N_CONTEXTS: M independent lanes, each a full context-pipeline,
    for M-times aggregate throughput. Flattened M-wide buses; a `generate` loop
    instantiates the (verified) per-lane wrapper. Compose with the context
    pipeline wrapper and the pipelined core."""
    n, m, c = int(num_rounds), int(num_pipelines), int(num_contexts)
    if m < 2:
        raise ValueError("num_pipelines must be >= 2")
    name = module_name or multi_pipeline_name(n, m, c)
    w = _ctx_width(c)
    lane = context_pipeline_name(n, c)
    return f"""// Generated by ascon_designspace.generator.structural
// M_PIPELINES_N_CONTEXTS: {m} parallel lanes of p[{n}], each interleaving {c}
// contexts -> {m}x aggregate throughput. Compose with {lane} and its core.
module {name} (
  input  wire             clk,
  input  wire             rst_n,
  input  wire [{m - 1}:0]       valid_i,
  input  wire [{m * w - 1}:0]   ctx_i,
  input  wire [{m * 320 - 1}:0]  state_i,
  output wire [{m - 1}:0]       valid_o,
  output wire [{m * w - 1}:0]   ctx_o,
  output wire [{m * 320 - 1}:0]  state_o
);
  genvar g;
  generate
    for (g = 0; g < {m}; g = g + 1) begin : lane
      {lane} u (
        .clk(clk), .rst_n(rst_n),
        .valid_i(valid_i[g]),
        .ctx_i(ctx_i[g*{w} +: {w}]),
        .state_i(state_i[g*320 +: 320]),
        .valid_o(valid_o[g]),
        .ctx_o(ctx_o[g*{w} +: {w}]),
        .state_o(state_o[g*320 +: 320])
      );
    end
  endgenerate
endmodule
"""


def emit_multi_pipeline_testbench(num_rounds: int, num_pipelines: int, num_contexts: int, *, module_name: str | None = None) -> str:
    n, m, c = int(num_rounds), int(num_pipelines), int(num_contexts)
    name = module_name or multi_pipeline_name(n, m, c)
    w = _ctx_width(c)
    ref = f"ascon_p{n}"
    # Per-lane queues and checkers, unrolled.
    decls = "\n".join(
        f"  reg [319:0] inq{g} [0:511];\n  reg [{w - 1}:0] cq{g} [0:511];\n"
        f"  integer wr{g} = 0, rd{g} = 0;"
        for g in range(m)
    )
    checks = "\n".join(
        f"""    if (rst_n && valid_o[{g}]) begin
      if (state_o[{g}*320 +: 320] !== {ref}(inq{g}[rd{g}])) begin errors = errors + 1; $display("LANE {g} DATA MISMATCH idx=%0d", rd{g}); end
      if (ctx_o[{g}*{w} +: {w}] !== cq{g}[rd{g}]) begin errors = errors + 1; $display("LANE {g} CTX MISMATCH idx=%0d", rd{g}); end
      trials = trials + 1; rd{g} = rd{g} + 1;
    end"""
        for g in range(m)
    )
    drive = "\n".join(
        f"""      state_i[{g}*320 +: 320] = {{$random,$random,$random,$random,$random,$random,$random,$random,$random,$random}};
      ctx_i[{g}*{w} +: {w}] = (i + {g}) % {c};
      inq{g}[wr{g}] = state_i[{g}*320 +: 320]; cq{g}[wr{g}] = (i + {g}) % {c}; wr{g} = wr{g} + 1;"""
        for g in range(m)
    )
    return f"""`timescale 1ns/1ps
module tb;
  reg              clk = 1'b0;
  reg              rst_n = 1'b0;
  reg  [{m - 1}:0]       valid_i = {m}'b0;
  reg  [{m * w - 1}:0]   ctx_i;
  reg  [{m * 320 - 1}:0]  state_i;
  wire [{m - 1}:0]       valid_o;
  wire [{m * w - 1}:0]   ctx_o;
  wire [{m * 320 - 1}:0]  state_o;

  {name} dut (
    .clk(clk), .rst_n(rst_n), .valid_i(valid_i),
    .ctx_i(ctx_i), .state_i(state_i),
    .valid_o(valid_o), .ctx_o(ctx_o), .state_o(state_o)
  );

  always #5 clk = ~clk;

{decls}
  integer errors = 0, trials = 0, i;

  always @(negedge clk) begin
{checks}
  end

  initial begin
    rst_n = 1'b0; repeat (3) @(negedge clk); rst_n = 1'b1;
    for (i = 0; i < 90; i = i + 1) begin
      @(negedge clk);
{drive}
      valid_i = {{{m}{{1'b1}}}};
    end
    @(negedge clk); valid_i = {m}'b0;
    repeat ({n} + 6) @(negedge clk);
    if (errors == 0) $display("PASS %0d trials 0 mismatches", trials);
    else             $display("FAIL %0d mismatches of %0d trials", errors, trials);
    $finish;
  end
endmodule
"""
