// SPDX-License-Identifier: MIT
// Tang Nano 9K high-throughput Ascon-p[12] pipeline smoke test.
// LED0: heartbeat
// LED1: p12(zero-state) self-test passed
// LED2: self-test failed
// LED3: pipeline output activity divider
// LED4: pipeline has produced at least one valid output
// LED5: pass and no failure

module tangnano9k_ascon_p12_pipeline_top(
  input  wire       clk,
  input  wire       btn1_n,
  output wire [5:0] led_n
);
  wire rst = ~btn1_n;

  localparam [319:0] ZERO_STATE = 320'h0;

  // Expected Ascon-p[12](ZERO_STATE), generated by the Python golden model:
  // x0=78ea7ae5cfebb108, x1=9b9bfb8513b560f7,
  // x2=6937f83e03d11a50, x3=3fe53f36f2c1178c,
  // x4=045d648e4def12c9.
  localparam [319:0] EXPECT_ZERO_P12 = 320'h045d648e4def12c9_3fe53f36f2c1178c_6937f83e03d11a50_9b9bfb8513b560f7_78ea7ae5cfebb108;

  reg [31:0] heartbeat_counter;
  reg [31:0] output_counter;
  reg [319:0] stimulus_state;
  reg test_sent;
  reg test_done;
  reg pass_latched;
  reg fail_latched;
  reg [11:0] test_pipe;

  wire [319:0] pipe_input_state = test_sent ? stimulus_state : ZERO_STATE;
  wire pipe_valid_i = 1'b1;
  wire pipe_valid_o;
  wire [319:0] pipe_state_o;
  wire test_output_now = pipe_valid_o & test_pipe[11];

  ascon_p12_pipeline u_p12_pipeline (
    .clk(clk),
    .rst(rst),
    .valid_i(pipe_valid_i),
    .state_i(pipe_input_state),
    .valid_o(pipe_valid_o),
    .state_o(pipe_state_o)
  );

  wire lfsr_feedback = stimulus_state[319] ^ stimulus_state[63] ^ stimulus_state[22] ^ stimulus_state[0];

  always @(posedge clk) begin
    if (rst) begin
      heartbeat_counter <= 32'b0;
      output_counter <= 32'b0;
      stimulus_state <= 320'h0123456789abcdef_fedcba9876543210_0f1e2d3c4b5a6978_8877665544332211_ffeeddccbbaa0099;
      test_sent <= 1'b0;
      test_done <= 1'b0;
      pass_latched <= 1'b0;
      fail_latched <= 1'b0;
      test_pipe <= 12'b0;
    end else begin
      heartbeat_counter <= heartbeat_counter + 32'd1;

      if (pipe_valid_o) begin
        output_counter <= output_counter + 32'd1;
      end

      // Keep the pipeline saturated after the first deterministic test vector.
      stimulus_state <= {stimulus_state[318:0], lfsr_feedback} ^
                        320'h0000000000000001_0000000000000000_0000000000000000_0000000000000000_0000000000000000;

      test_pipe <= {test_pipe[10:0], ~test_sent};
      test_sent <= 1'b1;

      if (test_output_now) begin
        test_done <= 1'b1;
        if (pipe_state_o == EXPECT_ZERO_P12) begin
          pass_latched <= 1'b1;
        end else begin
          fail_latched <= 1'b1;
        end
      end
    end
  end

  // Tang Nano 9K LEDs are active-low.
  assign led_n[0] = ~heartbeat_counter[24];
  assign led_n[1] = ~pass_latched;
  assign led_n[2] = ~fail_latched;
  assign led_n[3] = ~output_counter[23];
  assign led_n[4] = ~test_done;
  assign led_n[5] = ~(pass_latched & ~fail_latched);
endmodule
