#!/usr/bin/env python3
"""Prepare a deterministic Tang Nano 9K NEORV32 stream-ASCON board build package."""
from __future__ import annotations

import argparse
import json
import os
import shutil
from pathlib import Path
from typing import Any

from neorv32_stream_board_preflight import build_preflight_plan, validate_preflight_plan
from print_neorv32_stream_board_manifest import DEFAULT_MANIFEST, load_manifest, validate_manifest

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT = REPO_ROOT / "build" / "neorv32_stream_axis_mmio" / "package"


class BoardPackageError(RuntimeError):
    """Raised when the board build package cannot be generated or validated."""


def _rel(path: Path) -> str:
    return path.relative_to(REPO_ROOT).as_posix()


def _read_file_list(relpath: str) -> list[str]:
    path = REPO_ROOT / relpath
    return [
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]


def _split_sources(sources: list[str]) -> dict[str, list[str]]:
    verilog: list[str] = []
    vhdl: list[str] = []
    other: list[str] = []
    for source in sources:
        suffix = Path(source).suffix.lower()
        if suffix in {".v", ".vh", ".sv"}:
            verilog.append(source)
        elif suffix in {".vhd", ".vhdl"}:
            vhdl.append(source)
        else:
            other.append(source)
    return {"verilog": verilog, "vhdl": vhdl, "other": other}


def _write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _write_json(path: Path, payload: Any) -> None:
    _write_text(path, json.dumps(payload, indent=2, sort_keys=True) + "\n")


def _write_file_list(path: Path, sources: list[str]) -> None:
    _write_text(path, "\n".join(sources) + ("\n" if sources else ""))


def _firmware_header(defines: dict[str, str]) -> str:
    return "\n".join(
        [
            "#ifndef PYRILASCON_NEORV32_STREAM_AXIS_MMIO_CONFIG_H",
            "#define PYRILASCON_NEORV32_STREAM_AXIS_MMIO_CONFIG_H",
            "",
            "/* Generated by tools/prepare_neorv32_stream_board_build.py. */",
            "#define ASCON_BENCH_USE_AXIS_MMIO 1",
            f"#define ASCON_ACCEL_BASE_ADDR {defines['ASCON_ACCEL_BASE_ADDR']}",
            f"#define ASCON_ACCEL_AXIS_MMIO_BASE_ADDR {defines['ASCON_ACCEL_AXIS_MMIO_BASE_ADDR']}",
            "",
            "#endif /* PYRILASCON_NEORV32_STREAM_AXIS_MMIO_CONFIG_H */",
            "",
        ]
    )


def _firmware_make_fragment(firmware: dict[str, Any]) -> str:
    defines = firmware["defines"]
    return "\n".join(
        [
            "# Generated by tools/prepare_neorv32_stream_board_build.py.",
            "# Include or inspect this fragment when wiring the NEORV32 benchmark build.",
            "USE_CFS_AXIS_MMIO ?= 1",
            "ASCON_BENCH_USE_AXIS_MMIO ?= 1",
            f"ASCON_ACCEL_BASE_ADDR ?= {defines['ASCON_ACCEL_BASE_ADDR']}",
            f"ASCON_ACCEL_AXIS_MMIO_BASE_ADDR ?= {defines['ASCON_ACCEL_AXIS_MMIO_BASE_ADDR']}",
            "",
            "FIRMWARE_BUILD_COMMAND := " + firmware["command"],
            "",
        ]
    )


def _command_script(plan: dict[str, Any]) -> str:
    firmware = plan["firmware"]
    return "\n".join(
        [
            "#!/bin/sh",
            "set -eu",
            "",
            "# Generated board bring-up command sketch. Run from the repository root.",
            "python tools/print_neorv32_stream_board_manifest.py --check",
            "python tools/neorv32_stream_board_preflight.py --check",
            "python -m pytest -q tests/test_neorv32_stream_cfs_integration.py",
            "python -m pytest -q tests/test_stream_axis_mmio_system_sim.py",
            "make stream-axis-mmio-system-sim",
            "",
            "if [ -n \"${NEORV32_HOME:-}\" ]; then",
            "  make -C " + firmware["directory"] + " NEORV32_HOME=\"$NEORV32_HOME\" USE_CFS_AXIS_MMIO=1 clean_all exe",
            "else",
            "  echo 'Set NEORV32_HOME=/path/to/neorv32 to build firmware.'",
            "fi",
            "",
        ]
    )


def _readme(plan: dict[str, Any], source_split: dict[str, list[str]]) -> str:
    memory = plan["memory_map"]
    firmware = plan["firmware"]
    return "\n".join(
        [
            "# Tang Nano 9K NEORV32 stream ASCON build package",
            "",
            "This directory is generated by `tools/prepare_neorv32_stream_board_build.py`.",
            "It is a deterministic handoff package for the stream-native ASCON CFS target;",
            "it does not contain the upstream NEORV32 SoC checkout or vendor project files.",
            "",
            "## Memory map",
            "",
            f"- ASCON CSR/MMIO base: `{memory['csr_base']}`",
            f"- AXI-stream MMIO bridge base: `{memory['axis_mmio_base']}`",
            "",
            "## Firmware mode",
            "",
            f"- Directory: `{firmware['directory']}`",
            f"- Mode: `{firmware['make_mode']}`",
            "",
            "## RTL source lists",
            "",
            f"- `rtl_sources_all.f`: {len(source_split['verilog']) + len(source_split['vhdl']) + len(source_split['other'])} total sources",
            f"- `rtl_sources_verilog.f`: {len(source_split['verilog'])} Verilog/include sources",
            f"- `rtl_sources_vhdl.f`: {len(source_split['vhdl'])} VHDL sources",
            "",
            "Compile the VHDL wrapper into the NEORV32 library in place of the stock",
            "`neorv32_cfs.vhd` template. Compile the Verilog files as regular design sources.",
            "",
            "## Files",
            "",
            "- `manifest.json`: board manifest copy",
            "- `preflight.json`: host/tool/source readiness plan",
            "- `memory_map.json`: CSR and AXI-MMIO window addresses",
            "- `firmware/neorv32_stream_defines.mk`: firmware make defines",
            "- `firmware/ascon_stream_axis_mmio_config.h`: generated C defines",
            "- `commands.sh`: pre-board validation and firmware build sketch",
            "",
            "## Typical use",
            "",
            "```sh",
            "make neorv32-stream-board-package",
            "sh build/neorv32_stream_axis_mmio/package/commands.sh",
            "```",
            "",
        ]
    )


def prepare_package(
    out_dir: Path = DEFAULT_OUT,
    manifest_path: Path = DEFAULT_MANIFEST,
    neorv32_home: Path | None = None,
    clean: bool = False,
) -> dict[str, Any]:
    manifest = load_manifest(manifest_path)
    validate_manifest(manifest)
    plan = build_preflight_plan(manifest, neorv32_home)
    validate_preflight_plan(plan)

    if clean and out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    sources = _read_file_list(manifest["rtl"]["primary_file_list"])
    source_split = _split_sources(sources)

    memory_map = {
        "ascon_cfs_base": plan["memory_map"]["ascon_cfs_base"],
        "csr_base": plan["memory_map"]["csr_base"],
        "axis_mmio_base": plan["memory_map"]["axis_mmio_base"],
        "axis_mmio_offset": plan["memory_map"]["axis_mmio_offset"],
        "csr_size_bytes": manifest["memory_map"]["csr_window"]["size_bytes"],
        "axis_mmio_size_bytes": manifest["memory_map"]["axis_mmio_window"]["size_bytes"],
    }

    package = {
        "schema_version": 1,
        "name": "tangnano9k_neorv32_stream_axis_mmio_package",
        "manifest": manifest["name"],
        "output_dir": str(out_dir),
        "memory_map": memory_map,
        "firmware": plan["firmware"],
        "rtl": {
            "primary_file_list": manifest["rtl"]["primary_file_list"],
            "sources_total": len(sources),
            "verilog_sources": source_split["verilog"],
            "vhdl_sources": source_split["vhdl"],
            "other_sources": source_split["other"],
        },
        "generated_files": [
            "README.md",
            "manifest.json",
            "preflight.json",
            "package.json",
            "memory_map.json",
            "rtl_sources_all.f",
            "rtl_sources_verilog.f",
            "rtl_sources_vhdl.f",
            "firmware/neorv32_stream_defines.mk",
            "firmware/ascon_stream_axis_mmio_config.h",
            "commands.sh",
        ],
    }

    _write_text(out_dir / "README.md", _readme(plan, source_split))
    _write_json(out_dir / "manifest.json", manifest)
    _write_json(out_dir / "preflight.json", plan)
    _write_json(out_dir / "package.json", package)
    _write_json(out_dir / "memory_map.json", memory_map)
    _write_file_list(out_dir / "rtl_sources_all.f", sources)
    _write_file_list(out_dir / "rtl_sources_verilog.f", source_split["verilog"])
    _write_file_list(out_dir / "rtl_sources_vhdl.f", source_split["vhdl"])
    _write_text(out_dir / "firmware" / "neorv32_stream_defines.mk", _firmware_make_fragment(plan["firmware"]))
    _write_text(out_dir / "firmware" / "ascon_stream_axis_mmio_config.h", _firmware_header(plan["firmware"]["defines"]))
    commands = out_dir / "commands.sh"
    _write_text(commands, _command_script(plan))
    try:
        commands.chmod(commands.stat().st_mode | 0o111)
    except OSError:
        pass

    validate_package(out_dir)
    return package


def validate_package(out_dir: Path) -> None:
    package_path = out_dir / "package.json"
    if not package_path.exists():
        raise BoardPackageError(f"missing package metadata: {package_path}")
    package = json.loads(package_path.read_text(encoding="utf-8"))
    missing = [name for name in package["generated_files"] if not (out_dir / name).exists()]
    if missing:
        raise BoardPackageError(f"package is missing generated files: {', '.join(missing)}")

    memory = json.loads((out_dir / "memory_map.json").read_text(encoding="utf-8"))
    if memory["csr_base"].lower() != "0xffeb0000":
        raise BoardPackageError("unexpected CSR base in memory_map.json")
    if memory["axis_mmio_base"].lower() != "0xffeb0100":
        raise BoardPackageError("unexpected AXI-MMIO base in memory_map.json")

    all_sources = (out_dir / "rtl_sources_all.f").read_text(encoding="utf-8").splitlines()
    verilog_sources = (out_dir / "rtl_sources_verilog.f").read_text(encoding="utf-8").splitlines()
    vhdl_sources = (out_dir / "rtl_sources_vhdl.f").read_text(encoding="utf-8").splitlines()
    if len(all_sources) != len(verilog_sources) + len(vhdl_sources):
        raise BoardPackageError("split RTL file lists do not cover all sources")
    for source in all_sources:
        if not (REPO_ROOT / source).exists():
            raise BoardPackageError(f"source listed in package does not exist: {source}")

    firmware_header = (out_dir / "firmware" / "ascon_stream_axis_mmio_config.h").read_text(encoding="utf-8")
    if "ASCON_ACCEL_AXIS_MMIO_BASE_ADDR 0xFFEB0100u" not in firmware_header:
        raise BoardPackageError("firmware header does not define AXI-MMIO base")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--neorv32-home", type=Path, default=None, help="optional NEORV32 checkout path; defaults to NEORV32_HOME")
    parser.add_argument("--clean", action="store_true", help="remove the output directory before generating")
    parser.add_argument("--check", action="store_true", help="validate an existing generated package and print ok")
    parser.add_argument("--json", action="store_true", help="print package metadata JSON after generation")
    args = parser.parse_args()

    neorv32_home = args.neorv32_home
    if neorv32_home is None and os.environ.get("NEORV32_HOME"):
        neorv32_home = Path(os.environ["NEORV32_HOME"])

    if args.check:
        validate_package(args.out)
        print("ok")
        return 0

    package = prepare_package(args.out, args.manifest, neorv32_home, clean=args.clean)
    if args.json:
        print(json.dumps(package, indent=2, sort_keys=True))
    else:
        print(f"wrote {args.out}")
        print(f"sources: {package['rtl']['sources_total']} total, {len(package['rtl']['verilog_sources'])} Verilog, {len(package['rtl']['vhdl_sources'])} VHDL")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
