#!/usr/bin/env python3
"""Prepare a Tang Nano 9K Gowin handoff for the NEORV32 stream-ASCON target.

This tool does not synthesize or program hardware.  It turns the validated board
package into an archivable handoff directory containing source lists, memory-map
metadata, firmware build helpers, and command templates for the first real
Tang Nano / NEORV32 integration attempt.
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import stat
from pathlib import Path
from typing import Any

from prepare_neorv32_stream_board_build import DEFAULT_OUT as DEFAULT_PACKAGE_DIR, prepare_package, validate_package

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT = REPO_ROOT / "build" / "neorv32_stream_axis_mmio" / "gowin_handoff"


class GowinHandoffError(RuntimeError):
    """Raised when the Gowin handoff cannot be generated or validated."""


def _read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _write_json(path: Path, payload: Any) -> None:
    _write_text(path, json.dumps(payload, indent=2, sort_keys=True) + "\n")


def _make_executable(path: Path) -> None:
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def _read_file_list(path: Path) -> list[str]:
    return [line.strip() for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def _tool_status(name: str) -> dict[str, Any]:
    found = shutil.which(name)
    return {"available": found is not None, "path": found}


def _render_readme(handoff: dict[str, Any]) -> str:
    memory = handoff["memory_map"]
    tool_notes = handoff["toolchain_notes"]
    return "\n".join(
        [
            "# Tang Nano 9K NEORV32 stream-ASCON Gowin handoff",
            "",
            "This directory is generated by `tools/prepare_neorv32_stream_gowin_handoff.py`.",
            "It is a reproducible handoff for the first board build attempt; it does not",
            "vendor the upstream NEORV32 project and it does not program hardware by default.",
            "",
            "## Memory map",
            "",
            f"- ASCON CSR/MMIO base: `{memory['csr_base']}`",
            f"- AXI-stream MMIO bridge base: `{memory['axis_mmio_base']}`",
            "",
            "## Important toolchain note",
            "",
            "This target is mixed-language: the ASCON subsystem is Verilog and the NEORV32",
            "CFS wrapper is VHDL.  Plain Yosys/Gowin open-source flows usually need an",
            "upstream NEORV32 integration step or a VHDL-capable frontend before final",
            "synthesis.  This handoff therefore separates Verilog and VHDL sources and",
            "records tool availability instead of pretending a one-command bitstream flow",
            "exists today.",
            "",
            f"- Plain open-source flow ready: `{tool_notes['plain_open_source_flow_ready']}`",
            f"- Reason: {tool_notes['plain_open_source_flow_reason']}",
            "",
            "## Files",
            "",
            "- `handoff.json`: machine-readable handoff metadata",
            "- `memory_map.json`: firmware-visible base addresses",
            "- `sources/rtl_sources_verilog.f`: Verilog/include sources",
            "- `sources/rtl_sources_vhdl.f`: VHDL sources that must be compiled with NEORV32",
            "- `firmware/neorv32_stream_defines.mk`: firmware make flags",
            "- `scripts/01_preflight.sh`: regenerate and validate package/plan",
            "- `scripts/02_build_firmware.sh`: build benchmark firmware when `NEORV32_HOME` is set",
            "- `scripts/03_integrate_cfs.sh`: print the CFS wrapper integration action",
            "- `scripts/04_program_sram.sh`: guarded SRAM programming helper",
            "",
            "## Typical next actions",
            "",
            "```sh",
            "make neorv32-stream-gowin-handoff",
            "sh build/neorv32_stream_axis_mmio/gowin_handoff/scripts/01_preflight.sh",
            "NEORV32_HOME=/path/to/neorv32 sh build/neorv32_stream_axis_mmio/gowin_handoff/scripts/02_build_firmware.sh",
            "```",
            "",
            "After that, integrate `rtl/neorv32/neorv32_cfs_ascon_stream_axis_mmio.vhd` as",
            "the NEORV32 CFS implementation in your Tang Nano SoC project, build the FPGA",
            "image, capture UART output, and parse it with:",
            "",
            "```sh",
            "make neorv32-stream-uart-report LOG=/path/to/uart.log",
            "```",
            "",
        ]
    )


def _preflight_script() -> str:
    return "\n".join(
        [
            "#!/bin/sh",
            "set -eu",
            "cd \"$(dirname \"$0\")/../../../..\"",
            "python tools/print_neorv32_stream_board_manifest.py --check",
            "python tools/neorv32_stream_board_preflight.py --check",
            "python tools/prepare_neorv32_stream_board_build.py --check --out build/neorv32_stream_axis_mmio/package",
            "python tools/plan_neorv32_stream_board_build.py --ensure-package --write-defaults --check",
            "python tools/prepare_neorv32_stream_gowin_handoff.py --check --out build/neorv32_stream_axis_mmio/gowin_handoff",
            "echo 'Gowin handoff preflight ok.'",
            "",
        ]
    )


def _firmware_script() -> str:
    return "\n".join(
        [
            "#!/bin/sh",
            "set -eu",
            "cd \"$(dirname \"$0\")/../../../..\"",
            "if [ -z \"${NEORV32_HOME:-}\" ]; then",
            "  echo 'Set NEORV32_HOME=/path/to/neorv32 before building firmware.' >&2",
            "  exit 1",
            "fi",
            "make -C firmware/neorv32_ascon_benchmark NEORV32_HOME=\"$NEORV32_HOME\" USE_CFS_AXIS_MMIO=1 clean_all exe",
            "",
        ]
    )


def _cfs_script() -> str:
    return "\n".join(
        [
            "#!/bin/sh",
            "set -eu",
            "cat <<'EOF'",
            "Integrate this CFS wrapper into the NEORV32 SoC project:",
            "  rtl/neorv32/neorv32_cfs_ascon_stream_axis_mmio.vhd",
            "",
            "Compile these Verilog sources as design sources:",
            "  build/neorv32_stream_axis_mmio/gowin_handoff/sources/rtl_sources_verilog.f",
            "",
            "Compile these VHDL sources with the NEORV32 library:",
            "  build/neorv32_stream_axis_mmio/gowin_handoff/sources/rtl_sources_vhdl.f",
            "",
            "Firmware must use:",
            "  USE_CFS_AXIS_MMIO=1",
            "  ASCON_ACCEL_BASE_ADDR=0xFFEB0000u",
            "  ASCON_ACCEL_AXIS_MMIO_BASE_ADDR=0xFFEB0100u",
            "EOF",
            "",
        ]
    )


def _program_script() -> str:
    return "\n".join(
        [
            "#!/bin/sh",
            "set -eu",
            "if [ $# -ne 1 ]; then",
            "  echo 'usage: scripts/04_program_sram.sh /path/to/bitstream.fs' >&2",
            "  exit 2",
            "fi",
            "command -v openFPGALoader >/dev/null || { echo 'openFPGALoader not found' >&2; exit 1; }",
            "openFPGALoader -b tangnano9k \"$1\"",
            "",
        ]
    )


def _notes_md(handoff: dict[str, Any]) -> str:
    return "\n".join(
        [
            "# Manual Gowin/NEORV32 integration notes",
            "",
            "1. Build the NEORV32 benchmark firmware with `USE_CFS_AXIS_MMIO=1`.",
            "2. Replace or bind the NEORV32 CFS entity to `neorv32_cfs_ascon_stream_axis_mmio.vhd`.",
            "3. Compile the Verilog ASCON subsystem listed in `sources/rtl_sources_verilog.f`.",
            "4. Compile the CFS VHDL wrapper listed in `sources/rtl_sources_vhdl.f` with NEORV32.",
            "5. Build the Tang Nano image using your NEORV32 board top and pin constraints.",
            "6. Program SRAM with `scripts/04_program_sram.sh <bitstream.fs>`.",
            "7. Capture UART and parse it with `make neorv32-stream-uart-report LOG=<log>`.",
            "",
            "The generated handoff deliberately does not invent a board top or pinout for the",
            "full NEORV32 SoC. It records the ASCON CFS integration payload and the exact",
            "firmware/RTL contract that the board project must consume.",
            "",
            "## Expected UART proof",
            "",
            "A successful run should show hardware ciphertext/tag equality with the software",
            "reference, valid decrypt plaintext release, zero status/error codes, and a",
            "hardware cycle count lower than the software reference for the benchmark case.",
            "",
        ]
    )


def prepare_handoff(
    out_dir: Path = DEFAULT_OUT,
    package_dir: Path = DEFAULT_PACKAGE_DIR,
    clean: bool = False,
    ensure_package: bool = False,
) -> dict[str, Any]:
    if ensure_package and not (package_dir / "package.json").exists():
        prepare_package(package_dir, clean=True)
    validate_package(package_dir)

    if clean and out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    package = _read_json(package_dir / "package.json")
    memory = _read_json(package_dir / "memory_map.json")
    verilog_sources = _read_file_list(package_dir / "rtl_sources_verilog.f")
    vhdl_sources = _read_file_list(package_dir / "rtl_sources_vhdl.f")

    tools = {
        name: _tool_status(name)
        for name in [
            "yosys",
            "yowasp-yosys",
            "ghdl",
            "nextpnr-gowin",
            "nextpnr-himbaechel",
            "yowasp-nextpnr-himbaechel-gowin",
            "gowin_pack",
            "openFPGALoader",
        ]
    }
    vhdl_frontend_available = tools["ghdl"]["available"]
    yosys_available = tools["yosys"]["available"] or tools["yowasp-yosys"]["available"]
    pnr_available = tools["nextpnr-gowin"]["available"] or tools["nextpnr-himbaechel"]["available"] or tools["yowasp-nextpnr-himbaechel-gowin"]["available"]
    plain_open_source_flow_ready = bool(yosys_available and pnr_available and tools["gowin_pack"]["available"] and vhdl_frontend_available)

    handoff = {
        "schema_version": 1,
        "name": "tangnano9k_neorv32_stream_axis_mmio_gowin_handoff",
        "output_dir": str(out_dir),
        "package_dir": str(package_dir),
        "board": package["manifest"],
        "memory_map": memory,
        "firmware": package["firmware"],
        "rtl": {
            "verilog_sources": verilog_sources,
            "vhdl_sources": vhdl_sources,
            "verilog_count": len(verilog_sources),
            "vhdl_count": len(vhdl_sources),
            "cfs_wrapper": "rtl/neorv32/neorv32_cfs_ascon_stream_axis_mmio.vhd",
            "accelerator_system": "rtl/common/ascon_accel_stream_aead128_axis_mmio_system.v",
        },
        "tools": tools,
        "toolchain_notes": {
            "plain_open_source_flow_ready": plain_open_source_flow_ready,
            "plain_open_source_flow_reason": (
                "all required open-source tools including a VHDL frontend were found"
                if plain_open_source_flow_ready
                else "mixed Verilog/VHDL NEORV32 integration requires a VHDL-capable flow; generated files are a handoff, not a guaranteed one-command bitstream build"
            ),
        },
        "generated_files": [
            "README.md",
            "handoff.json",
            "memory_map.json",
            "sources/rtl_sources_verilog.f",
            "sources/rtl_sources_vhdl.f",
            "firmware/neorv32_stream_defines.mk",
            "firmware/ascon_stream_axis_mmio_config.h",
            "scripts/01_preflight.sh",
            "scripts/02_build_firmware.sh",
            "scripts/03_integrate_cfs.sh",
            "scripts/04_program_sram.sh",
            "notes/manual_gowin_integration.md",
        ],
    }

    _write_text(out_dir / "README.md", _render_readme(handoff))
    _write_json(out_dir / "handoff.json", handoff)
    _write_json(out_dir / "memory_map.json", memory)
    _write_text(out_dir / "sources" / "rtl_sources_verilog.f", "\n".join(verilog_sources) + "\n")
    _write_text(out_dir / "sources" / "rtl_sources_vhdl.f", "\n".join(vhdl_sources) + "\n")
    _write_text(
        out_dir / "firmware" / "neorv32_stream_defines.mk",
        (package_dir / "firmware" / "neorv32_stream_defines.mk").read_text(encoding="utf-8"),
    )
    _write_text(
        out_dir / "firmware" / "ascon_stream_axis_mmio_config.h",
        (package_dir / "firmware" / "ascon_stream_axis_mmio_config.h").read_text(encoding="utf-8"),
    )
    scripts = {
        "01_preflight.sh": _preflight_script(),
        "02_build_firmware.sh": _firmware_script(),
        "03_integrate_cfs.sh": _cfs_script(),
        "04_program_sram.sh": _program_script(),
    }
    for name, text in scripts.items():
        path = out_dir / "scripts" / name
        _write_text(path, text)
        _make_executable(path)
    _write_text(out_dir / "notes" / "manual_gowin_integration.md", _notes_md(handoff))

    validate_handoff(out_dir)
    return handoff


def validate_handoff(out_dir: Path = DEFAULT_OUT) -> None:
    handoff_path = out_dir / "handoff.json"
    if not handoff_path.exists():
        raise GowinHandoffError(f"missing handoff metadata: {handoff_path}")
    handoff = _read_json(handoff_path)
    missing = [name for name in handoff["generated_files"] if not (out_dir / name).exists()]
    if missing:
        raise GowinHandoffError("handoff is missing generated files: " + ", ".join(missing))

    memory = _read_json(out_dir / "memory_map.json")
    if memory["csr_base"].lower() != "0xffeb0000":
        raise GowinHandoffError("unexpected CSR base in handoff memory map")
    if memory["axis_mmio_base"].lower() != "0xffeb0100":
        raise GowinHandoffError("unexpected AXI-MMIO base in handoff memory map")

    verilog = _read_file_list(out_dir / "sources" / "rtl_sources_verilog.f")
    vhdl = _read_file_list(out_dir / "sources" / "rtl_sources_vhdl.f")
    if handoff["rtl"]["verilog_count"] != len(verilog):
        raise GowinHandoffError("Verilog source count mismatch")
    if handoff["rtl"]["vhdl_count"] != len(vhdl):
        raise GowinHandoffError("VHDL source count mismatch")
    if "rtl/common/ascon_accel_stream_aead128_axis_mmio_system.v" not in verilog:
        raise GowinHandoffError("accelerator system missing from Verilog source list")
    if "rtl/neorv32/neorv32_cfs_ascon_stream_axis_mmio.vhd" not in vhdl:
        raise GowinHandoffError("stream CFS wrapper missing from VHDL source list")

    for script in ["01_preflight.sh", "02_build_firmware.sh", "03_integrate_cfs.sh", "04_program_sram.sh"]:
        path = out_dir / "scripts" / script
        if not os.access(path, os.X_OK):
            raise GowinHandoffError(f"script is not executable: {path}")

    firmware_header = (out_dir / "firmware" / "ascon_stream_axis_mmio_config.h").read_text(encoding="utf-8")
    if "ASCON_ACCEL_AXIS_MMIO_BASE_ADDR 0xFFEB0100u" not in firmware_header:
        raise GowinHandoffError("firmware config header does not define the AXI-MMIO bridge base")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--package-dir", type=Path, default=DEFAULT_PACKAGE_DIR)
    parser.add_argument("--clean", action="store_true")
    parser.add_argument("--ensure-package", action="store_true", help="generate the board package first when missing")
    parser.add_argument("--check", action="store_true", help="validate an existing handoff directory")
    parser.add_argument("--json", action="store_true", help="print handoff metadata JSON")
    args = parser.parse_args()

    try:
        if args.check:
            validate_handoff(args.out)
            print("ok")
            return 0
        handoff = prepare_handoff(args.out, args.package_dir, clean=args.clean, ensure_package=args.ensure_package)
    except (GowinHandoffError, FileNotFoundError) as exc:
        print(f"error: {exc}", file=os.sys.stderr)
        return 1

    if args.json:
        print(json.dumps(handoff, indent=2, sort_keys=True))
    else:
        print(f"wrote {args.out}")
        print(f"sources: {handoff['rtl']['verilog_count']} Verilog, {handoff['rtl']['vhdl_count']} VHDL")
        print("plain_open_source_flow_ready:", handoff["toolchain_notes"]["plain_open_source_flow_ready"])
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
